import { BasePub } from './types';

export interface BermondseyPub extends BasePub {
  style: string;
  walkToNext: string | null;
}

export const bermondseyPubs: BermondseyPub[] = [
  {
    id: 1,
    pubName: 'The Kernel Brewery Taproom',
    address: '132 Spa Road',
    postcode: 'SE16 3AE',
    lat: 51.4960,
    lng: -0.0698,
    style: 'Pale ales & stouts',
    review: 'The brewery that started all of this. Evin O\'Riordain was a cheesemonger at Neal\'s Yard Dairy before a work trip to New York introduced him to American craft beer culture and he came home determined to brew. The Kernel opened in a Druid Street arch in September 2009, later moving to a bigger space on Spa Road. The Pale Ale \u2014 dry, bitter, different every batch depending on the hop \u2014 became a London modern classic. The taproom is concrete floor, no music, no food, just beer from the source. Opens Saturdays only. Get here early; the queue builds by 1pm and they sell out of the good stuff.',
    walkToNext: '5 min walk west',
    website: 'https://www.thekernelbrewery.com',
  },
  {
    id: 2,
    pubName: 'Mash Paddle Brewery',
    address: 'Railway Arch 92, Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4970,
    lng: -0.0710,
    style: 'Belgian-leaning & guest beers',
    review: 'Mash Paddle opened in 2022 and operates as something genuinely different on the Mile \u2014 a brewing membership club where you can actually brew your own beer on-site under guidance from their team, then come back three weeks later to collect it canned. The taproom is open to everyone, though, with up to 14 keg lines that lean Belgian. They run brewing classes on weekends and live music on Fridays. Open more days than most of the Mile \u2014 Wednesdays through Sundays \u2014 which makes it a useful midweek option if you\'re not doing the full Saturday pilgrimage.',
    walkToNext: '2 min walk',
    website: 'https://www.mashpaddlebrewery.com',
  },
  {
    id: 3,
    pubName: 'Enid Street Tavern',
    address: '87 Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4971,
    lng: -0.0712,
    style: 'Craft beer',
    review: 'For a while this was called The Dog House, which tells you something about the Beer Mile\'s rate of reinvention. Enid Street Tavern is the second taproom for Bianca Road Brew Co, reopened and renamed in 2023. Ten rotating taps, mostly from UK independent breweries, with Bianca Road\'s own beers in the mix. It\'s a small room and doesn\'t try to be anything more than that. You\'ll pass it between the bigger names on Enid Street, and it\'s worth ducking in precisely because it isn\'t trying to impress you.',
    walkToNext: '1 min walk',
    website: 'https://enidstreettavern.com',
  },
  {
    id: 4,
    pubName: 'Craft Beer Junction',
    address: '86 Enid Street',
    postcode: 'SE16 3RD',
    lat: 51.4972,
    lng: -0.0714,
    style: 'Rare imports & nano-brewery',
    review: 'If you\'ve ever wanted to drink a fresh American IPA in London without the usual import lag, this is the place. Marcin Clos founded Craft Beer Junction in 2021 as an import operation \u2014 air-freighting American craft beer to keep it as fresh as possible \u2014 and the bar under Arch 86 followed. Ten taps plus a serious fridge of cans and bottles, heavy on US breweries you won\'t find anywhere else in the city. They added a nano-brewery in 2024 for their own stuff. Also a good place to pick up something to take home; the bottle shop side is just as strong as the bar.',
    walkToNext: '2 min walk',
    website: 'https://www.craftbeerjunction.co.uk',
  },
  {
    id: 5,
    pubName: 'Bianca Road Brew Co',
    address: '83 Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4973,
    lng: -0.0717,
    style: 'Small-batch & experimental',
    review: 'Bianca Road started in Peckham in 2016, moved to Bermondsey a year later, and has been quietly building a reputation for small-batch, experimental beers that change constantly. The tap list is different every visit \u2014 they don\'t repeat themselves and they don\'t play safe. The taproom sits in a large double-fronted arch on Enid Street and the brewers are usually on the other side of the bar, which means you can actually ask what you\'re drinking and get an honest answer. Dennis Ratliff, previously head brewer at Brew By Numbers and Partizan, joined the team recently.',
    walkToNext: '1 min walk',
    website: 'https://biancaroad.com',
  },
  {
    id: 6,
    pubName: 'Cloudwater',
    address: 'Arch 79, Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4977,
    lng: -0.0726,
    style: 'IPAs & pale ales',
    review: 'Manchester\'s most celebrated craft brewery, and the only UK brewery ever ranked in RateBeer\'s global top ten \u2014 they made it in both 2017 and 2018. The Bermondsey taproom at 73 Enid Street has 19 draft taps and a cask handpull, pouring beer brewed up north and shipped down. The IPAs are what they\'re known for: clean, hop-forward, and consistently among the best in the country. The space is more polished than some of the grittier arches nearby, which is either a relief or a disappointment depending on what you\'re looking for. Expect a queue on Saturday afternoons.',
    walkToNext: 'Next door',
    website: 'https://cloudwaterbrew.co',
  },
  {
    id: 7,
    pubName: 'Gosnells',
    address: 'Arch 72-73, Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4977,
    lng: -0.0726,
    style: 'Mead',
    review: 'The wildcard. Gosnells makes mead, not beer, and if your only reference point for mead is a medieval fair, you\'re going to be surprised. Tom Gosnell founded the company in Peckham in 2013 and opened this Bermondsey taproom in September 2022. Everything is brewed with British blossom honey \u2014 no refined sugars \u2014 and the results are closer to a dry cider or a natural wine than to anything you\'d associate with a tankard. Try the hopped variety. The taproom is small and the staff will walk you through the range if you ask, which you should, because the menu makes more sense with context.',
    walkToNext: '5 min walk',
    website: 'https://www.gosnells.co.uk',
  },
  {
    id: 8,
    pubName: 'Anspach & Hobday',
    address: 'Arch 118, Druid Street',
    postcode: 'SE1 2HH',
    lat: 51.4987,
    lng: -0.0735,
    style: 'Porter & mixed styles',
    review: 'Paul Anspach and Jack Hobday have been friends since childhood. They started homebrewing at university, Kickstarted \u00a35,000 for their first proper brew kit, and opened on Druid Street in 2013 with two beers: a Smoked Brown and a porter. The porter won. Anspach & Hobday\'s London Black \u2014 a nitro porter with a long chocolate-roast finish \u2014 has become one of London\'s definitive craft beers, and the brewery leans deliberately into London\'s porter heritage, the style that was born in this city three centuries ago. They\'ve since expanded production to Croydon, but the Bermondsey taproom remains. Twelve taps, usually busy.',
    walkToNext: '2 min walk',
    website: 'https://www.anspachandhobday.com',
  },
  {
    id: 9,
    pubName: 'Hiver Taproom',
    address: '56 Stanworth Street',
    postcode: 'SE1 3NY',
    lat: 51.4989,
    lng: -0.0747,
    style: 'Honey beer',
    review: 'Every beer here is brewed with British honey, which gives the range a sweetness that sits somewhere between a blonde ale and something you\'d find at a farm shop. Hiver\'s taproom is lighter and airier than most of the arches \u2014 they\'ve clearly put thought into making the space feel less industrial. The real draw, though, is that it sits right at the foot of Maltby Street Market, and they\'ll let you bring street food in if you buy a beer. Sunny urban beer garden out front. They also run beekeeping experiences if you want to meet the bees responsible for what you\'re drinking.',
    walkToNext: '2 min walk',
    website: 'https://hiverbeers.com',
  },
  {
    id: 10,
    pubName: 'The Barrel Project',
    address: 'Arch 80, Druid Street',
    postcode: 'SE1 2EZ',
    lat: 51.4996,
    lng: -0.0755,
    style: 'Barrel-aged & sours',
    review: 'Two hundred oak barrels \u2014 Bordeaux and Burgundy casks, mostly \u2014 line the walls of this railway arch, and 24 taps pour what comes out of them. The Barrel Project is London Beer Factory\'s dedicated blendery and taproom, open since late 2018, and it\'s the stop on the Mile for sour and barrel-aged beer. The interior genuinely looks like a wine cellar that switched allegiances. If you\'re the sort of person who orders a Flemish red or a spontaneously fermented ale when they\'re on the menu, you could spend the entire afternoon here and not make it to the last three stops. We say this from experience.',
    walkToNext: '2 min walk',
    website: 'https://thebarrelproject.co.uk',
  },
  {
    id: 11,
    pubName: 'The Doodle Bar',
    address: '60 Druid Street',
    postcode: 'SE1 2EZ',
    lat: 51.5002,
    lng: -0.0763,
    style: 'Craft beer & cocktails',
    review: 'Not a brewery. Not trying to be. The Doodle Bar started as a pop-up in a Battersea warehouse in 2009 and has since landed in this railway arch on Druid Street, where the walls are giant chalkboards and bowls of chalk sit on every table. Craft beers, cocktails, ping pong, table football, burgers. The furniture is made from old boats, which is the kind of detail that sounds made up but isn\'t. Capacity of around 250, so it rarely feels squeezed, and it\'s a good pressure valve if your group has hit hop fatigue and needs a round of something that isn\'t an IPA.',
    walkToNext: '2 min walk',
    website: 'https://www.thedoodlebar.com',
  },
  {
    id: 12,
    pubName: 'Southwark Brewing Company',
    address: '46 Druid Street',
    postcode: 'SE1 2EZ',
    lat: 51.5006,
    lng: -0.0771,
    style: 'Traditional English ale',
    review: 'Southwark Brewing opened in autumn 2014 and has been quietly doing its own thing while flashier operations have come and gone around it. Their focus is traditional English cask ale \u2014 six handpumps pouring real ale in an area where nearly everyone else is on keg. The Bermondsey Best is an English bitter, the kind of straightforward, well-made pint that doesn\'t need a tasting note or a flavour wheel. The brewery sits near the former sites of Barclay Perkins and Courage\'s Horsleydown brewery, which makes the traditionalist stance feel less like nostalgia and more like a geographical argument.',
    walkToNext: '3 min walk',
    website: 'https://www.southwarkbrewing.co.uk',
  },
  {
    id: 13,
    pubName: 'Hop Kingdom',
    address: '16 Druid Street',
    postcode: 'SE1 2EY',
    lat: 51.5020,
    lng: -0.0796,
    style: 'Craft beer & skatepark',
    review: 'An indoor skatepark and bar spanning two railway arches \u2014 and yes, that\'s a real sentence about a real place on a pub crawl. Hop Kingdom opened in 2018 after founder Ben Hopkinson noticed there were almost no indoor skateboarding facilities in London and decided to fix that in the most Bermondsey way possible: stick a bar next to it. The first arch has the bar and a mini ramp; the second has a street-style skating section. A skate session costs \u00a36.50 and includes a drink. Two Hop King own beers on tap, plus cans and spirits. Adults only after 6pm. You don\'t have to skate to drink here, but you will be watching people skate while you drink, which at stop thirteen on the Beer Mile is frankly all the entertainment you need.',
    walkToNext: null,
    website: 'https://hopking.org',
  },
];

export const bermondseyStats = {
  totalPubs: bermondseyPubs.length,
  estimatedTime: '4\u20136 hours',
  area: 'Bermondsey',
};
