import { BasePub } from './types';

export interface BermondseyPub extends BasePub {
  style: string;
  walkToNext: string | null;
}

export const bermondseyPubs: BermondseyPub[] = [
  {
    id: 1,
    pubName: 'The Kernel Brewery Taproom',
    address: '132 Spa Road',
    postcode: 'SE16 3AE',
    lat: 51.4960,
    lng: -0.0698,
    style: 'Pale ales & stouts',
    review: 'The Kernel started the Bermondsey Beer Mile before anyone called it that. Evin O\'Riordain founded the brewery in 2010 under a railway arch, and The Kernel\'s Pale Ale — dry, bitter, loaded with American hops — became a London modern classic. The taproom is bare-bones: concrete floor, no frills, just exceptional beer at source. Opens Saturdays only.',
    walkToNext: '5 min walk west',
  },
  {
    id: 2,
    pubName: 'Mash Paddle Brewery',
    address: 'Railway Arch 92, Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4970,
    lng: -0.0710,
    style: 'Belgian-leaning & guest beers',
    review: 'Mash Paddle Brewery is a brewing membership club and taproom that doubles as an incubator for start-up brewers. Up to 14 keg lines with a Belgian focus, live music on Fridays, and pizza on Saturdays. A newer addition to the Mile that\'s already earned its spot.',
    walkToNext: '2 min walk',
  },
  {
    id: 3,
    pubName: 'Enid Street Tavern',
    address: '87 Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4971,
    lng: -0.0712,
    style: 'Craft beer',
    review: 'Enid Street Tavern opened in 2023 as a second taproom for Bianca Road Brewery. Eight keg taps pour Enid Street-branded beers brewed by Bianca Road alongside rotating guests. A small, relaxed space between the bigger names on the Mile.',
    walkToNext: '1 min walk',
  },
  {
    id: 4,
    pubName: 'Craft Beer Junction',
    address: '86 Enid Street',
    postcode: 'SE16 3RD',
    lat: 51.4972,
    lng: -0.0714,
    style: 'Rare imports & nano-brewery',
    review: 'Craft Beer Junction is a bar and bottle shop specialising in rare American imports alongside UK and international beers. Founded in 2021 by beer importer Marcin Clos, with up to 10 taps plus a huge fridge of cans and bottles. They added an on-site nano-brewery in 2024. A good place to pick up something to take home.',
    walkToNext: '2 min walk',
  },
  {
    id: 5,
    pubName: 'Bianca Road Brew Co',
    address: '83 Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4973,
    lng: -0.0717,
    style: 'Small-batch & experimental',
    review: 'Bianca Road Brew Co is one of the Mile\'s newer operations, founded by a former Kernel brewer. Small-batch and experimental — the tap list changes every visit and they don\'t do safe or predictable. The taproom is intimate and the brewers are usually pouring their own beer.',
    walkToNext: '1 min walk',
  },
  {
    id: 6,
    pubName: 'Cloudwater',
    address: 'Arch 79, Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4977,
    lng: -0.0726,
    style: 'IPAs & pale ales',
    review: 'Cloudwater is Manchester\'s most celebrated craft brewery, with a permanent Bermondsey taproom. Their IPAs and pale ales are consistently among the best in the UK — clean, balanced, and unapologetically hop-forward. The taproom is more polished than some of the grittier arches on the Mile. Usually has a queue on Saturday afternoons.',
    walkToNext: 'Next door',
  },
  {
    id: 7,
    pubName: 'Gosnells',
    address: 'Arch 72-73, Enid Street',
    postcode: 'SE16 3RA',
    lat: 51.4977,
    lng: -0.0726,
    style: 'Mead',
    review: 'Gosnells is the wildcard on the Bermondsey Beer Mile — they make mead, not beer. Every batch is brewed with British honey, and if you think mead is a novelty for medieval fairs, Gosnells will change your mind. Try the citra-hopped variety. Small, friendly taproom.',
    walkToNext: '5 min walk',
  },
  {
    id: 8,
    pubName: 'Anspach & Hobday',
    address: 'Arch 118, Druid Street',
    postcode: 'SE1 2HH',
    lat: 51.4987,
    lng: -0.0735,
    style: 'Porter & mixed styles',
    review: 'Anspach & Hobday is one of the Bermondsey Beer Mile\'s anchor breweries, established in 2013. Their Porter — rich, roasty, with a long chocolate finish — is a proper London porter in the tradition of the style that was invented in this city. Twelve taps, usually busy, reliably excellent.',
    walkToNext: '2 min walk',
  },
  {
    id: 9,
    pubName: 'Hiver Taproom',
    address: '56 Stanworth Street',
    postcode: 'SE1 3NY',
    lat: 51.4989,
    lng: -0.0747,
    style: 'Honey beer',
    review: 'Hiver Taproom brews every beer with British honey, giving the range a distinctive sweetness you won\'t find elsewhere on the Mile. The taproom is lighter and airier than most of the arches, with the Beer Mile\'s biggest outdoor seating area. Right next to Maltby Street Market — combine the two on a Saturday.',
    walkToNext: '2 min walk',
  },
  {
    id: 10,
    pubName: 'The Barrel Project',
    address: 'Arch 80, Druid Street',
    postcode: 'SE1 2EZ',
    lat: 51.4996,
    lng: -0.0755,
    style: 'Barrel-aged & sours',
    review: 'The Barrel Project is a London Beer Factory spin-off dedicated entirely to barrel-aged and sour beers. Two hundred oak barrels line the walls and 24 taps pour the results. The interior looks like a wine cellar that switched sides. If you like sours and wild ales, The Barrel Project is the highlight of the Mile.',
    walkToNext: '2 min walk',
  },
  {
    id: 11,
    pubName: 'The Doodle Bar',
    address: '60 Druid Street',
    postcode: 'SE1 2EZ',
    lat: 51.5002,
    lng: -0.0763,
    style: 'Craft beer & cocktails',
    review: 'The Doodle Bar is a warehouse-style bar in a railway arch where the walls are giant chalkboards and you\'re encouraged to draw on them. Craft beers, cocktails, ping pong, and burgers — not a brewery, but a good place to take a breather from the hops. Capacity of around 250, so it rarely feels crowded.',
    walkToNext: '2 min walk',
  },
  {
    id: 12,
    pubName: 'Southwark Brewing Company',
    address: '46 Druid Street',
    postcode: 'SE1 2EZ',
    lat: 51.5006,
    lng: -0.0771,
    style: 'Traditional English ale',
    review: 'Southwark Brewing Company is one of the longest-running operations on the Bermondsey Beer Mile. Their Bermondsey Best is an English bitter — the kind of straightforward, well-made pint that doesn\'t need a backstory or a flavour wheel. A solid, unpretentious stop near the western end of the Mile.',
    walkToNext: '3 min walk',
  },
  {
    id: 13,
    pubName: 'Hop Kingdom',
    address: '16 Druid Street',
    postcode: 'SE1 2EY',
    lat: 51.5020,
    lng: -0.0796,
    style: 'Craft beer & skatepark',
    review: 'Hop Kingdom is an indoor skatepark and bar spanning two railway arches on the Bermondsey Beer Mile — free to skate, free to enter for drinkers. Run by Hop King, the associated beer brand, with own-brand beers on tap and in cans. Adults only after 6pm. Not your typical taproom.',
    walkToNext: null,
  },
];

export const bermondseyStats = {
  totalPubs: bermondseyPubs.length,
  estimatedTime: '4\u20136 hours',
  area: 'Bermondsey',
};
