// Circle Line Pub Crawl - 27 stations, 27 pubs

export interface CircleLinePub {
  id: number;
  station: string;
  pubName: string;
  address: string;
  postcode: string;
  lat: number;
  lng: number;
  rating: number;
  startTime: string;
  endTime: string;
  transportToNext: 'Circle Line' | null;
  transportTime: number | null;
  review: string;
  website?: string;
  image?: string;
}

export const circleLinePubs: CircleLinePub[] = [
  {
    id: 1,
    station: 'Edgware Road',
    pubName: 'The Chapel',
    address: '48 Chapel Street',
    postcode: 'NW1 5DP',
    lat: 51.5198,
    lng: -0.1676,
    rating: 7,
    startTime: '10:00',
    endTime: '10:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A stylish gastropub near Edgware Road with a good selection of craft beers. Perfect starting point for the Circle Line Challenge with a solid breakfast menu to line your stomach.',
    website: 'https://www.chapelbar.co.uk',
  },
  {
    id: 2,
    station: 'Paddington',
    pubName: 'The Victoria',
    address: '10A Strathearn Place',
    postcode: 'W2 2NH',
    lat: 51.5155,
    lng: -0.1793,
    rating: 7,
    startTime: '10:35',
    endTime: '11:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A traditional Victorian pub tucked away near Paddington Station. Good real ales and a cosy atmosphere. Gets the crawl properly started.',
  },
  {
    id: 3,
    station: 'Bayswater',
    pubName: 'The Mitre',
    address: '24 Craven Terrace',
    postcode: 'W2 3QH',
    lat: 51.5126,
    lng: -0.1876,
    rating: 6,
    startTime: '11:05',
    endTime: '11:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A reliable local near Bayswater station. Nothing fancy but serves a good pint and keeps you moving on the crawl.',
  },
  {
    id: 4,
    station: 'Notting Hill Gate',
    pubName: 'The Coronet',
    address: '338-346 Holloway Road',
    postcode: 'W11 3HX',
    lat: 51.5094,
    lng: -0.1963,
    rating: 6,
    startTime: '11:35',
    endTime: '12:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A Wetherspoons in a converted cinema. Cheap drinks and quick service - essential for keeping up the pace on a 27-pub crawl.',
    website: 'https://www.jdwetherspoon.com',
  },
  {
    id: 5,
    station: 'High Street Kensington',
    pubName: 'The Elephant & Castle',
    address: '40 Holland Street',
    postcode: 'W8 4LT',
    lat: 51.5016,
    lng: -0.1927,
    rating: 7,
    startTime: '12:05',
    endTime: '12:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A charming backstreet pub in Kensington with excellent Fuller\'s ales. A proper London local tucked away from the high street bustle.',
  },
  {
    id: 6,
    station: 'Gloucester Road',
    pubName: 'The Stanhope Arms',
    address: '97 Gloucester Road',
    postcode: 'SW7 4SS',
    lat: 51.4943,
    lng: -0.1828,
    rating: 7,
    startTime: '12:35',
    endTime: '13:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Traditional pub right by the station. Good spot for a quick half and keeping the momentum going through South Kensington.',
    website: 'https://www.stanhopearms.co.uk',
  },
  {
    id: 7,
    station: 'South Kensington',
    pubName: 'The Hoop & Toy',
    address: '34 Thurloe Place',
    postcode: 'SW7 2HQ',
    lat: 51.4941,
    lng: -0.1744,
    rating: 7,
    startTime: '13:05',
    endTime: '13:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A handsome Victorian pub opposite the V&A. Great people-watching from the terrace and solid pub food if you need to refuel.',
  },
  {
    id: 8,
    station: 'Sloane Square',
    pubName: 'The Antelope',
    address: '22 Eaton Terrace',
    postcode: 'SW1W 8EZ',
    lat: 51.4928,
    lng: -0.1575,
    rating: 8,
    startTime: '13:35',
    endTime: '14:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A proper Chelsea pub with a traditional interior and excellent ales. One of the highlights of the southern arc of the Circle Line.',
    website: 'https://www.antelopepub.com',
  },
  {
    id: 9,
    station: 'Victoria',
    pubName: 'The Cask Pub & Kitchen',
    address: '6 Charlwood Street',
    postcode: 'SW1V 2EE',
    lat: 51.4908,
    lng: -0.1407,
    rating: 8,
    startTime: '14:05',
    endTime: '14:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A craft beer paradise with 10 cask ales and dozens of keg lines. Essential stop for beer lovers. One of the best pubs on the whole crawl.',
    website: 'https://www.caskpubandkitchen.com',
  },
  {
    id: 10,
    station: 'St James\'s Park',
    pubName: 'The Red Lion',
    address: '48 Parliament Street',
    postcode: 'SW1A 2NH',
    lat: 51.5012,
    lng: -0.1268,
    rating: 7,
    startTime: '14:35',
    endTime: '15:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A Westminster institution where MPs and civil servants have been drinking for centuries. The division bell still rings for Commons votes.',
    website: 'https://www.redlionwestminster.co.uk',
  },
  {
    id: 11,
    station: 'Westminster',
    pubName: 'St Stephen\'s Tavern',
    address: '10 Bridge Street',
    postcode: 'SW1A 2JR',
    lat: 51.5007,
    lng: -0.1246,
    rating: 8,
    startTime: '15:05',
    endTime: '15:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A magnificent Victorian pub opposite Big Ben with ornate glass and woodwork. Political history oozes from every corner. A must-visit.',
    website: 'https://www.ststephenstavern.co.uk',
  },
  {
    id: 12,
    station: 'Embankment',
    pubName: 'The Sherlock Holmes',
    address: '10 Northumberland Street',
    postcode: 'WC2N 5DB',
    lat: 51.5070,
    lng: -0.1235,
    rating: 7,
    startTime: '15:35',
    endTime: '16:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Themed pub with a recreation of Holmes\' study upstairs. Touristy but fun, and conveniently close to the station.',
    website: 'https://www.sherlockholmespub.com',
  },
  {
    id: 13,
    station: 'Temple',
    pubName: 'The Edgar Wallace',
    address: '40 Essex Street',
    postcode: 'WC2R 3JE',
    lat: 51.5118,
    lng: -0.1124,
    rating: 7,
    startTime: '16:05',
    endTime: '16:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Named after the crime writer who lived nearby. A solid lawyers\' pub in the heart of legal London. Good ales and a literary atmosphere.',
  },
  {
    id: 14,
    station: 'Blackfriars',
    pubName: 'The Blackfriar',
    address: '174 Queen Victoria Street',
    postcode: 'EC4V 4EG',
    lat: 51.5120,
    lng: -0.1035,
    rating: 9,
    startTime: '16:35',
    endTime: '17:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The most extraordinary pub interior in London. An Arts and Crafts masterpiece with marble walls and bronze friars. Nearly demolished in 1964 but saved by John Betjeman\'s campaign. Unmissable.',
    website: 'https://www.nicholsonspubs.co.uk/theblackfriarlondon',
  },
  {
    id: 15,
    station: 'Mansion House',
    pubName: 'The Counting House',
    address: '50 Cornhill',
    postcode: 'EC3V 3PD',
    lat: 51.5131,
    lng: -0.0864,
    rating: 8,
    startTime: '17:05',
    endTime: '17:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A former bank transformed into a spectacular pub. The domed ceiling and chandeliers are genuinely breathtaking. Fuller\'s ales in banking hall splendour.',
    website: 'https://www.the-counting-house.com',
  },
  {
    id: 16,
    station: 'Cannon Street',
    pubName: 'The Bell',
    address: '29 Bush Lane',
    postcode: 'EC4R 0AN',
    lat: 51.5119,
    lng: -0.0904,
    rating: 6,
    startTime: '17:35',
    endTime: '18:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A small City pub hidden down an alley. Perfect for a quick drink between stations. Closed weekends so weekday crawls only.',
  },
  {
    id: 17,
    station: 'Monument',
    pubName: 'The Monument',
    address: '18 Fish Street Hill',
    postcode: 'EC3R 6DB',
    lat: 51.5100,
    lng: -0.0860,
    rating: 7,
    startTime: '18:05',
    endTime: '18:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Right at the foot of the Monument to the Great Fire. A solid City pub with good views and a convenient location.',
    website: 'https://www.monumentpub.co.uk',
  },
  {
    id: 18,
    station: 'Tower Hill',
    pubName: 'The Hung Drawn and Quartered',
    address: '26-27 Great Tower Street',
    postcode: 'EC3R 5AQ',
    lat: 51.5100,
    lng: -0.0785,
    rating: 7,
    startTime: '18:35',
    endTime: '19:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Named after the gruesome fate of traitors at the nearby Tower. A large Fuller\'s pub with good food and views toward the Tower of London.',
    website: 'https://www.hung-drawn-and-quartered.co.uk',
  },
  {
    id: 19,
    station: 'Aldgate',
    pubName: 'The Hoop and Grapes',
    address: '47 Aldgate High Street',
    postcode: 'EC3N 1AL',
    lat: 51.5142,
    lng: -0.0758,
    rating: 8,
    startTime: '19:05',
    endTime: '19:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'One of the few timber-framed buildings to survive both the Great Fire and the Blitz. The crooked floors and leaning walls are part of the charm. Historic and atmospheric.',
    website: 'https://www.hoopandgrapes.co.uk',
  },
  {
    id: 20,
    station: 'Liverpool Street',
    pubName: 'Hamilton Hall',
    address: 'Liverpool Street Station',
    postcode: 'EC2M 7PY',
    lat: 51.5178,
    lng: -0.0823,
    rating: 8,
    startTime: '19:35',
    endTime: '20:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A former ballroom inside Liverpool Street station with extraordinary gilded ceilings and baroque plasterwork. One of London\'s most spectacular pub interiors, inexplicably inside a train station.',
    website: 'https://www.jdwetherspoon.com',
  },
  {
    id: 21,
    station: 'Moorgate',
    pubName: 'The Globe',
    address: '83 Moorgate',
    postcode: 'EC2M 6SA',
    lat: 51.5182,
    lng: -0.0889,
    rating: 6,
    startTime: '20:05',
    endTime: '20:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A reliable City pub with a good range of ales. Not the most exciting stop but keeps the crawl moving through the northern City.',
  },
  {
    id: 22,
    station: 'Barbican',
    pubName: 'The Butchers Hook & Cleaver',
    address: '61 West Smithfield',
    postcode: 'EC1A 9DY',
    lat: 51.5193,
    lng: -0.1015,
    rating: 7,
    startTime: '20:35',
    endTime: '21:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A Fuller\'s pub next to Smithfield Market with a proper Victorian interior. Named after the historic meat market trade. Great atmosphere in the evenings.',
    website: 'https://www.butchershookandcleaver.co.uk',
  },
  {
    id: 23,
    station: 'Farringdon',
    pubName: 'The Jerusalem Tavern',
    address: '55 Britton Street',
    postcode: 'EC1M 5UQ',
    lat: 51.5221,
    lng: -0.1049,
    rating: 9,
    startTime: '21:05',
    endTime: '21:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A tiny, perfectly preserved 18th-century pub serving St Peter\'s ales from Suffolk. One of London\'s best small pubs with genuine character. A Circle Line highlight.',
    website: 'https://www.stpetersbrewery.co.uk/jerusalem-tavern',
  },
  {
    id: 24,
    station: 'King\'s Cross St Pancras',
    pubName: 'The Parcel Yard',
    address: 'King\'s Cross Station',
    postcode: 'N1C 4AH',
    lat: 51.5306,
    lng: -0.1240,
    rating: 7,
    startTime: '21:35',
    endTime: '22:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A vast Fuller\'s pub in the restored Victorian parcel office at King\'s Cross. Great architecture and a good selection of ales to see you into the final stretch.',
    website: 'https://www.parcelyard.co.uk',
  },
  {
    id: 25,
    station: 'Euston Square',
    pubName: 'The Euston Flyer',
    address: '83-87 Euston Road',
    postcode: 'NW1 2RA',
    lat: 51.5256,
    lng: -0.1349,
    rating: 6,
    startTime: '22:05',
    endTime: '22:30',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A large Wetherspoons opposite Euston station. Cheap drinks and late opening - essential for the final push of the Circle Line Challenge.',
    website: 'https://www.jdwetherspoon.com',
  },
  {
    id: 26,
    station: 'Great Portland Street',
    pubName: 'The Albany',
    address: '240 Great Portland Street',
    postcode: 'W1W 5QU',
    lat: 51.5236,
    lng: -0.1439,
    rating: 7,
    startTime: '22:35',
    endTime: '23:00',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A stylish pub on Great Portland Street with good cocktails and ales. The penultimate stop - you\'re nearly there.',
    website: 'https://www.thealbany.co.uk',
  },
  {
    id: 27,
    station: 'Baker Street',
    pubName: 'The Volunteer',
    address: '245 Baker Street',
    postcode: 'NW1 6XE',
    lat: 51.5226,
    lng: -0.1571,
    rating: 7,
    startTime: '23:05',
    endTime: '23:30',
    transportToNext: null,
    transportTime: null,
    review: 'You made it! A proper Victorian pub near Baker Street station to celebrate completing the Circle Line Challenge. 27 stations, 27 pubs, one legend.',
    website: 'https://www.volunteernw1.co.uk',
  },
];

// Calculate stats
export const circleLineStats = {
  totalPubs: circleLinePubs.length,
  totalStations: 27,
  estimatedTime: '13.5 hours',
  totalTubeTime: circleLinePubs.reduce((acc, pub) => acc + (pub.transportTime || 0), 0),
};

// Helper to get Google Maps URL for a pub
export function getCircleLineMapsUrl(pub: CircleLinePub): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${pub.pubName}, ${pub.address}, ${pub.postcode}`)}`;
}

// Helper to get directions from one pub to the next
export function getCircleLineDirectionsUrl(fromPub: CircleLinePub, toPub: CircleLinePub): string {
  const origin = encodeURIComponent(`${fromPub.pubName}, ${fromPub.address}`);
  const destination = encodeURIComponent(`${toPub.pubName}, ${toPub.address}`);
  return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=transit`;
}
