// Circle Line Pub Crawl - 27 stations, 27 pubs
// Route: King's Cross westbound, looping back to Farringdon

import { BasePub } from './types';

export interface CircleLinePub extends BasePub {
  station: string;
  rating: number;
  startTime: string;
  endTime: string;
  transportToNext: 'Circle Line' | null;
  transportTime: number | null;
}

export const circleLinePubs: CircleLinePub[] = [
  {
    id: 1,
    station: 'King\'s Cross St Pancras',
    pubName: 'The Parcel Yard',
    address: 'King\'s Cross Station',
    postcode: 'N1C 4AH',
    lat: 51.5306,
    lng: -0.1240,
    rating: 7,
    startTime: '10:00',
    endTime: '10:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Parcel Yard opens at 8am, which makes it the earliest start on the Circle Line and the obvious launchpad. It sits in the restored Victorian parcel office above King\'s Cross \u2014 the old Great Northern Railway mail depot, built in 1852 and converted into a Fuller\'s pub in 2012. Two floors, multiple drinking areas, original industrial features, and a view down onto the station concourse through a double-height atrium. Prince Charles came for the opening. Get a proper breakfast here and take your time \u2014 you have twenty-six pubs ahead of you, and the pace picks up fast after this one.',
    website: 'https://www.parcelyard.co.uk',
  },
  {
    id: 2,
    station: 'Euston Square',
    pubName: 'The Euston Flyer',
    address: '83-87 Euston Road',
    postcode: 'NW1 2RA',
    lat: 51.5256,
    lng: -0.1349,
    rating: 6,
    startTime: '10:30',
    endTime: '10:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A big Fuller\'s pub opposite Euston station, the Euston Flyer opens at 9am on Saturdays and gets the crawl\'s second drink out of the way without fuss. The interior is decorated with old railway photos, including one of the original Euston Arch that was demolished in 1961 \u2014 a decision so controversial it helped launch the conservation movement. There\'s sport on the screens and a standard Fuller\'s menu if you\'re doubling up on breakfast. Service is quick, which matters more than ambience at this stage.',
    website: 'https://www.eustonflyer.co.uk',
  },
  {
    id: 3,
    station: 'Great Portland Street',
    pubName: 'The Albany',
    address: '240 Great Portland Street',
    postcode: 'W1W 5QU',
    lat: 51.5236,
    lng: -0.1439,
    rating: 7,
    startTime: '11:00',
    endTime: '11:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Albany dates to the 1860s and was rebuilt in 1898, though it spent a brief identity crisis as the Fitz & Firkin in 1996 before reverting to its proper name. This is Fitzrovia \u2014 the neighbourhood that gave us Orwell and Dylan Thomas \u2014 and the pub has a basement venue called the LowDown that hosts comedy and live music. It had a full refurbishment in 2023 that kept the bones intact while widening the beer range. Opens at 11am on Saturdays, so the timing slots in neatly from the Euston Flyer. Don\'t get comfortable in the basement.',
    website: 'https://www.thealbany.co.uk',
  },
  {
    id: 4,
    station: 'Baker Street',
    pubName: 'The Volunteer',
    address: '245 Baker Street',
    postcode: 'NW1 6XE',
    lat: 51.5226,
    lng: -0.1571,
    rating: 7,
    startTime: '11:30',
    endTime: '11:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Named after the Royal Marylebone Volunteers formed during the Napoleonic Wars, The Volunteer sits a few doors from 221B Baker Street \u2014 or where it would be if it existed. The building dates to around 1815 and is Grade II listed. Underneath it are the original cellars from the Neville family mansion that burned down in 1654, which may explain why staff report a ghost in breeches and a surcoat. The wood-panelled interior mixes period features with enough modernity to keep it from feeling like a museum. A proper settling-in pub for the early phase of the crawl.',
    website: 'https://www.volunteernw1.co.uk',
  },
  {
    id: 5,
    station: 'Edgware Road',
    pubName: 'The Green Man',
    address: '308 Edgware Road',
    postcode: 'W2 1DY',
    lat: 51.5200,
    lng: -0.1680,
    rating: 6,
    startTime: '12:00',
    endTime: '12:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The oldest surviving licensed premises on Edgware Road, dating from 1720. The Green Man was rebuilt in 1867 as a mid-Victorian corner pub with etched bow windows and a marbled facade, and in 2007 it became the birthplace of PubLove \u2014 the hostel-above-a-pub concept now found across London. Backpackers sleep upstairs; you drink downstairs. Craft beer and burgers are the main draws. It\'s right next to the station, which at this point in the crawl you\'ll appreciate more than architecture.',
    website: 'https://www.publove.co.uk/pubs/green-man',
  },
  {
    id: 6,
    station: 'Paddington',
    pubName: 'The Victoria',
    address: '10A Strathearn Place',
    postcode: 'W2 2NH',
    lat: 51.5155,
    lng: -0.1793,
    rating: 7,
    startTime: '12:30',
    endTime: '12:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Built in 1837 \u2014 the year Queen Victoria took the throne, which is either coincidence or marketing \u2014 The Victoria on Strathearn Place is Grade II listed with one of the oldest surviving mahogany bars in the country. The back fittings date to 1864, and upstairs you\'ll find fixtures salvaged from the Gaiety Theatre after it was demolished in 1957. Legend says Dickens wrote parts of Our Mutual Friend here. Fuller\'s Pub of the Year in 2007 and 2009, CAMRA West London Pub of the Year in 2024. We\'d linger if the crawl allowed it.',
  },
  {
    id: 7,
    station: 'Bayswater',
    pubName: 'The Mitre',
    address: '24 Craven Terrace',
    postcode: 'W2 3QH',
    lat: 51.5126,
    lng: -0.1876,
    rating: 6,
    startTime: '13:00',
    endTime: '13:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Grade II listed and a two-star entry on CAMRA\'s National Inventory \u2014 that\'s \u201cinterior of very special national historic interest,\u201d which is not a phrase they throw around. The Mitre was Lord Craven\'s town house before it became a pub in 1859, and the first-floor dining rooms are still named after him. Look for the etched glass, the mosaic floors, and the door panels advertising a \u201cladies only\u201d snug that no longer enforces its policy. A Young\'s pub with an unusual pair of curved entrance doors at the corner. You\'ll be in and out quickly, but notice the glass on your way through.',
    website: 'https://www.themitrehydepark.com',
  },
  {
    id: 8,
    station: 'Notting Hill Gate',
    pubName: 'The Churchill Arms',
    address: '119 Kensington Church Street',
    postcode: 'W8 7LN',
    lat: 51.5070,
    lng: -0.1927,
    rating: 8,
    startTime: '13:30',
    endTime: '13:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'You\'ll recognise it before you reach it. The Churchill Arms spends twenty-five thousand pounds a year on flowers, and the result is the most photographed pub exterior in London \u2014 hanging baskets and window boxes from pavement to roofline. Named after Winston Churchill\'s grandparents, who were regulars when it was still the Bedford Arms in the 1820s. Inside: Churchill memorabilia, Fuller\'s ales, and what claims to be London\'s first pub Thai restaurant, running since the late 1980s in a butterfly-themed conservatory out back. Three minutes from Notting Hill Gate station. The only pub to have won Chelsea Flower Show.',
    website: 'https://www.churchillarmskensington.co.uk',
  },
  {
    id: 9,
    station: 'High Street Kensington',
    pubName: 'The Elephant & Castle',
    address: '40 Holland Street',
    postcode: 'W8 4LT',
    lat: 51.5016,
    lng: -0.1927,
    rating: 7,
    startTime: '14:00',
    endTime: '14:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'First licensed as a beer house in 1865, The Elephant & Castle on Holland Street has barely been touched since a 1950s refit that left it looking like a time capsule. The Charrington\'s three-sided mirrored bar-back is the centrepiece \u2014 illuminated panels lettered \u201cWines & Spirits\u201d and \u201cToby Ale\u201d with a small Toby jug image on the right. Historic front pages line the walls, a nod to the journalists who\'ve been drinking here for decades. A backstreet Kensington pub that rewards you for finding it.',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/theelephantandcastlekensingtonlondon',
  },
  {
    id: 10,
    station: 'Gloucester Road',
    pubName: 'The Stanhope Arms',
    address: '97 Gloucester Road',
    postcode: 'SW7 4SS',
    lat: 51.4943,
    lng: -0.1828,
    rating: 7,
    startTime: '14:30',
    endTime: '14:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Built in 1869 when this stretch was called Stanhope Terrace, after the Earls of Harrington who owned the land. The wedge-shaped building has gold-painted pilasters on the ground floor and an Edwardian bar-back with mirrored panels and a broken pediment. CAMRA lists it as a one-star National Inventory pub. The bar counter is still in its original position, having once served three separate rooms that have since been opened up. A Greene King pub right opposite Gloucester Road station \u2014 grab a half and keep moving south.',
    website: 'https://www.stanhopearms.co.uk',
  },
  {
    id: 11,
    station: 'South Kensington',
    pubName: 'The Hoop & Toy',
    address: '34 Thurloe Place',
    postcode: 'SW7 2HQ',
    lat: 51.4941,
    lng: -0.1744,
    rating: 7,
    startTime: '15:00',
    endTime: '15:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Probably the oldest established tavern in Kensington, dating to around 1515 when it was called the Grapes. The name changed to Hoop & Grapes, then Hoop & Toy in 1784 \u2014 the \u201ctoy\u201d being a rum-soaked leather peg used to stop horses grinding their teeth, which is the kind of fact you can\'t make up. The pub sits opposite the V&A, and its history includes a connection to London\'s first congestion charge in 1796: the owner built a second pub up the road to dodge the toll at Brompton Gate. Rebuilt in 1844, front redone in red brick in 1927.',
    website: 'https://www.greeneking.co.uk/pubs/greater-london/hoop-and-toy',
  },
  {
    id: 12,
    station: 'Sloane Square',
    pubName: 'The Antelope',
    address: '22 Eaton Terrace',
    postcode: 'SW1W 8EZ',
    lat: 51.4928,
    lng: -0.1575,
    rating: 8,
    startTime: '15:30',
    endTime: '15:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Two front doors, one pub. The Antelope was built in 1827 for the servants of the Belgravia gentry \u2014 one entrance for the butler and grander household staff, another for those of lower rank. Both doors are still there, but the class system inside has flattened to pin-stripe suits and builders sharing the island bar. It\'s a Fuller\'s pub on a quiet Eaton Terrace side street near Sloane Square, with etched glass windows and wood-panelled rooms upstairs. The southern arc of the crawl is about to get good \u2014 savour this one.',
    website: 'https://www.antelopepub.com',
  },
  {
    id: 13,
    station: 'Victoria',
    pubName: 'The Cask Pub & Kitchen',
    address: '6 Charlwood Street',
    postcode: 'SW1V 2EE',
    lat: 51.4908,
    lng: -0.1407,
    rating: 8,
    startTime: '16:00',
    endTime: '16:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'London\'s first craft beer-focused pub, opened in 2009 in a former estate pub on Charlwood Street. Ten handpumps, around twenty keg lines, and a cellar of over two thousand vintage bottles \u2014 some of the last examples in the world, curated since day one. The building is Grade II listed, the corner-site layout is compact, and on Sundays there\'s live folk music from half four. CAMRA branch Pub of the Year in 2019 and again in 2025. If you\'re going to spend an extra ten minutes anywhere on the crawl, spend them here. Order a half of something you\'ve never heard of.',
    website: 'https://www.caskpubandkitchen.com',
  },
  {
    id: 14,
    station: 'St James\'s Park',
    pubName: 'The Red Lion',
    address: '48 Parliament Street',
    postcode: 'SW1A 2NH',
    lat: 51.5012,
    lng: -0.1268,
    rating: 7,
    startTime: '16:30',
    endTime: '16:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A tavern called Hopping Hall stood on this spot as early as 1434. The current Red Lion dates from about 1890, and its regulars are MPs, lobbyists, and civil servants \u2014 it sits on Parliament Street, a minute\'s walk from Downing Street and the Palace of Westminster. The division bell is still installed, though it\'s largely ceremonial now that MPs have phones. Charles Dickens visited as a boy. The occasional ringing still confuses tourists who think it\'s a fire alarm.',
    website: 'https://www.redlionwestminster.co.uk',
  },
  {
    id: 15,
    station: 'Westminster',
    pubName: 'St Stephen\'s Tavern',
    address: '10 Bridge Street',
    postcode: 'SW1A 2JR',
    lat: 51.5007,
    lng: -0.1246,
    rating: 8,
    startTime: '17:00',
    endTime: '17:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Named after St Stephen\'s Chapel, the original meeting place of the House of Commons. There\'s been a pub here since at least the eighteenth century, but the current building dates from 1875 \u2014 French Renaissance architecture, Grade II listed, with ornate ceilings you can inspect from a Victorian-era mezzanine. Baldwin, Churchill, and Macmillan all drank here. The pub closed in the 1980s during Jubilee Line construction and Portcullis House building work, then reopened in 2003 after a full restoration by Hall & Woodhouse. The division bell was restored at the same time. Big Ben is directly across the road.',
    website: 'https://www.ststephenstavern.co.uk',
  },
  {
    id: 16,
    station: 'Embankment',
    pubName: 'The Sherlock Holmes',
    address: '10 Northumberland Street',
    postcode: 'WC2N 5DB',
    lat: 51.5070,
    lng: -0.1235,
    rating: 7,
    startTime: '17:30',
    endTime: '17:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Until 1957, this was the Northumberland Arms \u2014 and before that, the Northumberland Hotel, which may be the one Conan Doyle used in The Hound of the Baskervilles. Whitbread bought the entire Festival of Britain Sherlock Holmes exhibit after its world tour and installed it upstairs: a full recreation of 221B Baker Street behind plate glass, curated by the Sherlock Holmes Society of London. The building dates from 1736. It\'s a Greene King pub now, and yes, it\'s touristy, but the recreation is genuinely detailed \u2014 Persian slipper for the tobacco, gasogene for Watson\'s soda, jack-knife for the correspondence.',
    website: 'https://www.sherlockholmespub.com',
  },
  {
    id: 17,
    station: 'Temple',
    pubName: 'Temple Brew House',
    address: '46 Essex Street',
    postcode: 'WC2R 3JF',
    lat: 51.5118,
    lng: -0.1120,
    rating: 7,
    startTime: '18:00',
    endTime: '18:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'An independent brewpub on Essex Street with a five-barrel brew house visible from the bar and from street level. Opened in 2014 as the Essex Street Brewery, it became Temple Brew House after a 2022 refit following a two-year closure. The basement \u2014 which is said to be the original street level from the 1670s, when entrepreneur Nicholas Barbon redeveloped the old Essex House grounds \u2014 is where the brewing happens. Part of the City Pub Group\'s micro-brew chain alongside Bath and Cambridge. Right next to Temple station.',
    website: 'https://www.templebrewhouse.com',
  },
  {
    id: 18,
    station: 'Blackfriars',
    pubName: 'The Blackfriar',
    address: '174 Queen Victoria Street',
    postcode: 'EC4V 4EG',
    lat: 51.5120,
    lng: -0.1035,
    rating: 9,
    startTime: '18:30',
    endTime: '18:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The most extraordinary pub interior in London, and we\'re not being hyperbolic. Built in 1875 on the site of a Dominican friary, the ground-floor interior was redesigned around 1905 by architect H. Fuller-Clark and artist Henry Poole in an Arts and Crafts style that borders on the hallucinatory: marble walls, bronze reliefs of jolly friars, mosaic ceilings, and carved aphorisms like \u201cHaste Is Slow\u201d above the bar. In the 1960s it was nearly demolished for a road-widening scheme. John Betjeman led the campaign that saved it. CAMRA National Inventory. Stop rushing. Drink slowly. Look up.',
    website: 'https://www.nicholsonspubs.co.uk/theblackfriarlondon',
  },
  {
    id: 19,
    station: 'Mansion House',
    pubName: 'Ye Olde Watling',
    address: '29 Watling Street',
    postcode: 'EC4M 9BR',
    lat: 51.5128,
    lng: -0.0936,
    rating: 7,
    startTime: '19:00',
    endTime: '19:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Rebuilt by Christopher Wren in 1668 to house the workers constructing St Paul\'s Cathedral, using timber salvaged from decommissioned ships. The plans for St Paul\'s were supposedly drawn up in what is now the dining room upstairs. The old-world timber-framed interior largely dates from a sympathetic 1901 refit. Open Saturdays noon to 8pm \u2014 the crawl arrives around 7pm, so check the time and don\'t dawdle at Blackfriars. A Nicholson\'s pub on the ancient Roman road of Watling Street. You\'re in the City now, and the City closes early.',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/yeoldewatlingwatlingstreetlondon',
  },
  {
    id: 20,
    station: 'Cannon Street',
    pubName: 'The Hydrant',
    address: '1 Monument Street',
    postcode: 'EC3R 8BG',
    lat: 51.5104,
    lng: -0.0876,
    rating: 7,
    startTime: '19:30',
    endTime: '19:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A Fuller\'s pub at the foot of the Monument, renamed in 2015 from The Fine Line with a light fire-brigade theme \u2014 appropriate given it\'s two hundred feet from where the Great Fire started. The building is modern, the beer range is decent, and the main virtue at this stage of the crawl is that it opens on Saturdays when most City pubs don\'t. If you need food, this is your last reliable chance before the final push.',
    website: 'https://www.thehydrant.co.uk',
  },
  {
    id: 21,
    station: 'Monument',
    pubName: 'The Monument',
    address: '18 Fish Street Hill',
    postcode: 'EC3R 6DB',
    lat: 51.5100,
    lng: -0.0860,
    rating: 7,
    startTime: '20:00',
    endTime: '20:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A Greene King pub at 18 Fish Street Hill, directly beneath the Monument to the Great Fire. The column itself is 202 feet tall and 202 feet from the Pudding Lane bakery where the fire began in 1666 \u2014 designed by Robert Hooke, not Wren, which is worth knowing for pub-quiz purposes. The pub is a straightforward City local: cask ales, British menu, screens showing sport. At this point you\'re twenty pubs deep and the quality of the architecture matters less than the fact that it\'s open and serving.',
    website: 'https://www.monumentpub.co.uk',
  },
  {
    id: 22,
    station: 'Tower Hill',
    pubName: 'The Hung Drawn and Quartered',
    address: '26-27 Great Tower Street',
    postcode: 'EC3R 5AQ',
    lat: 51.5100,
    lng: -0.0785,
    rating: 7,
    startTime: '20:30',
    endTime: '20:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Named after the execution method historically performed at nearby Tower Hill, where everyone from the Archbishop of Canterbury (1381) to Lord Lovat (1747, the last public execution on the site) lost their heads. The building was a bank, and before that part of Christ\'s Hospital, a school founded in 1552. It\'s a Fuller\'s Ale & Pie pub now, Grade II listed, with high ceilings, wood panelling, and portraits of monarchs on the walls. Views toward the Tower of London if you can still focus.',
    website: 'https://www.hung-drawn-and-quartered.co.uk',
  },
  {
    id: 23,
    station: 'Aldgate',
    pubName: 'The Hoop and Grapes',
    address: '47 Aldgate High Street',
    postcode: 'EC3N 1AL',
    lat: 51.5142,
    lng: -0.0758,
    rating: 8,
    startTime: '21:00',
    endTime: '21:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Great Fire of 1666 stopped fifty yards short of this building. That\'s why it\'s still standing \u2014 one of the few sixteenth-century timber-framed structures left in the City. The front leans noticeably outward, held together by extensive restoration work, and the floors inside are not level. Grade II* listed. The exposed wooden beams and period windows are the real thing, not a reproduction. Opposite Aldgate station. You\'re in the home stretch now \u2014 four pubs to go.',
    website: 'https://www.hoopandgrapes.co.uk',
  },
  {
    id: 24,
    station: 'Liverpool Street',
    pubName: 'Hamilton Hall',
    address: 'Liverpool Street Station',
    postcode: 'EC2M 7PY',
    lat: 51.5178,
    lng: -0.0823,
    rating: 8,
    startTime: '21:30',
    endTime: '21:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Wetherspoon\'s first-ever station pub, opened in 1991 inside the former ballroom of the Great Eastern Hotel at Liverpool Street. Named after Lord Claud Hamilton, chairman of the Great Eastern Railway from 1893 to 1923. The Rococo interior \u2014 modelled on the Palais Soubise in Paris during a 1901 redesign \u2014 is Grade II* listed: gilded plasterwork, painted panels, and a mezzanine that once held the ballroom orchestra. It is a genuinely surreal place to have your twenty-fourth drink. Cheap, grand, and always busier than you\'d expect.',
    website: 'https://www.jdwetherspoon.com',
  },
  {
    id: 25,
    station: 'Moorgate',
    pubName: 'The Globe',
    address: '83 Moorgate',
    postcode: 'EC2M 6SA',
    lat: 51.5182,
    lng: -0.0889,
    rating: 6,
    startTime: '22:00',
    endTime: '22:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A Nicholson\'s pub on a prominent Moorgate corner, with an elaborate French classical stucco facade that dates from an 1870s refit of an early-nineteenth-century building. The name comes from the Portuguese globe emblem, advertising the fine Portuguese wines once served here. In 2008 it absorbed the neighbouring John Keats pub \u2014 named for the Romantic poet who may have been born on the site in 1795, though this is disputed. Late in the crawl, low on glamour, but it keeps a decent range of cask ales and it\'s open when you need it to be.',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/theglobemoorgatelondon',
  },
  {
    id: 26,
    station: 'Barbican',
    pubName: 'Fox & Anchor',
    address: '115 Charterhouse Street',
    postcode: 'EC1M 6AA',
    lat: 51.5199,
    lng: -0.1009,
    rating: 8,
    startTime: '22:30',
    endTime: '22:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Art Nouveau tiled facade \u2014 running from pavement to roofline gable, dated 1898 \u2014 was designed by William J. Neatby of Doulton & Co., the same artist who did the interior of Harrods\' food hall. The Fox & Anchor sits on the edge of Smithfield Market and held one of London\'s early-morning licences: it used to open at 6:30am for the meat porters. Black-and-white portraits of the butchers and porters line the interior. Open until 1am on Saturdays, with six bedrooms upstairs if the crawl has broken you. The penultimate stop \u2014 Farringdon is ten minutes away.',
    website: 'https://www.foxandanchor.com',
  },
  {
    id: 27,
    station: 'Farringdon',
    pubName: 'The Holy Tavern',
    address: '55 Britton Street',
    postcode: 'EC1M 5UQ',
    lat: 51.5221,
    lng: -0.1049,
    rating: 9,
    startTime: '23:00',
    endTime: '23:25',
    transportToNext: null,
    transportTime: null,
    review: 'You made it. Formerly the Jerusalem Tavern \u2014 renamed in 2022 when St Peter\'s Brewery didn\'t renew the lease, but otherwise unchanged. The building is a 1720 town house with an 1810 shopfront, and it became a pub in 1996 when it was leased to St Peter\'s as their only London outlet. It\'s tiny, perfectly preserved, and still serves St Peter\'s ales from Suffolk. The site sits within the old grounds of the Clerkenwell Priory, headquarters of the Knights Hospitaller in England. Last orders come early, so don\'t linger at Fox & Anchor. Twenty-seven stations, twenty-seven pubs.',
    website: 'https://theholytavern.com',
  },
];

// Calculate stats
export const circleLineStats = {
  totalPubs: circleLinePubs.length,
  totalStations: 27,
  estimatedTime: '13.5 hours',
  totalTubeTime: circleLinePubs.reduce((acc, pub) => acc + (pub.transportTime || 0), 0),
};
