// Circle Line Pub Crawl - 27 stations, 27 pubs
// Route: King's Cross westbound, looping back to Farringdon

import { BasePub } from './types';

export interface CircleLinePub extends BasePub {
  station: string;
  rating: number;
  startTime: string;
  endTime: string;
  transportToNext: 'Circle Line' | null;
  transportTime: number | null;
}

export const circleLinePubs: CircleLinePub[] = [
  {
    id: 1,
    station: 'King\'s Cross St Pancras',
    pubName: 'The Parcel Yard',
    address: 'King\'s Cross Station',
    postcode: 'N1C 4AH',
    lat: 51.5306,
    lng: -0.1240,
    rating: 7,
    startTime: '10:00',
    endTime: '10:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Parcel Yard opens at 8am - the earliest on the Circle Line — making it the ideal launchpad. A vast Fuller\'s pub in the restored Victorian parcel office at King\'s Cross. Great architecture, a solid breakfast menu, and a good selection of ales to line your stomach before the long haul ahead.',
    website: 'https://www.parcelyard.co.uk',
  },
  {
    id: 2,
    station: 'Euston Square',
    pubName: 'The Euston Flyer',
    address: '83-87 Euston Road',
    postcode: 'NW1 2RA',
    lat: 51.5256,
    lng: -0.1349,
    rating: 6,
    startTime: '10:30',
    endTime: '10:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Euston Flyer opens at 9am on Saturdays — one of the few pubs on the line ready this early. A large Fuller\'s pub opposite Euston station. Cheap drinks and quick service to keep you moving.',
    website: 'https://www.eustonflyer.co.uk',
  },
  {
    id: 3,
    station: 'Great Portland Street',
    pubName: 'The Albany',
    address: '240 Great Portland Street',
    postcode: 'W1W 5QU',
    lat: 51.5236,
    lng: -0.1439,
    rating: 7,
    startTime: '11:00',
    endTime: '11:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Albany is a stylish pub on Great Portland Street with good cocktails and ales. Opens at 11am on Saturdays — the timing works perfectly from the Euston Flyer.',
    website: 'https://www.thealbany.co.uk',
  },
  {
    id: 4,
    station: 'Baker Street',
    pubName: 'The Volunteer',
    address: '245 Baker Street',
    postcode: 'NW1 6XE',
    lat: 51.5226,
    lng: -0.1571,
    rating: 7,
    startTime: '11:30',
    endTime: '11:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A proper Victorian pub near Baker Street station. Solid ales, traditional interior, and a good atmosphere to settle into the rhythm of the crawl.',
    website: 'https://www.volunteernw1.co.uk',
  },
  {
    id: 5,
    station: 'Edgware Road',
    pubName: 'The Green Man',
    address: '308 Edgware Road',
    postcode: 'W2 1DY',
    lat: 51.5200,
    lng: -0.1680,
    rating: 6,
    startTime: '12:00',
    endTime: '12:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Green Man sits right next to Edgware Road station. A PubLove pub with craft beers, burgers, and a relaxed atmosphere. Opens at 9am daily, though by now you won\'t need the early start.',
    website: 'https://www.publove.co.uk/pubs/green-man',
  },
  {
    id: 6,
    station: 'Paddington',
    pubName: 'The Victoria',
    address: '10A Strathearn Place',
    postcode: 'W2 2NH',
    lat: 51.5155,
    lng: -0.1793,
    rating: 7,
    startTime: '12:30',
    endTime: '12:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Victoria is a traditional Victorian pub tucked away near Paddington Station. Good real ales and a cosy atmosphere. Gets the western arc properly started.',
  },
  {
    id: 7,
    station: 'Bayswater',
    pubName: 'The Mitre',
    address: '24 Craven Terrace',
    postcode: 'W2 3QH',
    lat: 51.5126,
    lng: -0.1876,
    rating: 6,
    startTime: '13:00',
    endTime: '13:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Mitre is a reliable local near Bayswater station. Nothing fancy but serves a good pint and keeps you moving on the crawl. Opens at noon — the route is timed so you arrive right on cue.',
  },
  {
    id: 8,
    station: 'Notting Hill Gate',
    pubName: 'The Churchill Arms',
    address: '119 Kensington Church Street',
    postcode: 'W8 7LN',
    lat: 51.5070,
    lng: -0.1927,
    rating: 8,
    startTime: '13:30',
    endTime: '13:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Churchill Arms is one of London\'s most recognisable pubs, its exterior smothered in flowers and hanging baskets. A proper Fuller\'s pub with excellent ales and legendary Thai food served in the conservatory out back. Named after Winston Churchill\'s grandparents, who were regulars. Three minutes from Notting Hill Gate station.',
    website: 'https://www.churchillarmskensington.co.uk',
  },
  {
    id: 9,
    station: 'High Street Kensington',
    pubName: 'The Elephant & Castle',
    address: '40 Holland Street',
    postcode: 'W8 4LT',
    lat: 51.5016,
    lng: -0.1927,
    rating: 7,
    startTime: '14:00',
    endTime: '14:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Elephant & Castle is a charming backstreet pub in Kensington with excellent Fuller\'s ales. A proper London local tucked away from the high street bustle.',
  },
  {
    id: 10,
    station: 'Gloucester Road',
    pubName: 'The Stanhope Arms',
    address: '97 Gloucester Road',
    postcode: 'SW7 4SS',
    lat: 51.4943,
    lng: -0.1828,
    rating: 7,
    startTime: '14:30',
    endTime: '14:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Stanhope Arms is a traditional pub right by the station. Good spot for a quick half and keeping the momentum going through South Kensington.',
    website: 'https://www.stanhopearms.co.uk',
  },
  {
    id: 11,
    station: 'South Kensington',
    pubName: 'The Hoop & Toy',
    address: '34 Thurloe Place',
    postcode: 'SW7 2HQ',
    lat: 51.4941,
    lng: -0.1744,
    rating: 7,
    startTime: '15:00',
    endTime: '15:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Hoop & Toy is a handsome Victorian pub opposite the V&A. Great people-watching from the terrace and solid pub food if you need to refuel.',
  },
  {
    id: 12,
    station: 'Sloane Square',
    pubName: 'The Antelope',
    address: '22 Eaton Terrace',
    postcode: 'SW1W 8EZ',
    lat: 51.4928,
    lng: -0.1575,
    rating: 8,
    startTime: '15:30',
    endTime: '15:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Antelope is a proper Chelsea pub with a traditional interior and excellent ales. One of the highlights of the southern arc of the Circle Line.',
    website: 'https://www.antelopepub.com',
  },
  {
    id: 13,
    station: 'Victoria',
    pubName: 'The Cask Pub & Kitchen',
    address: '6 Charlwood Street',
    postcode: 'SW1V 2EE',
    lat: 51.4908,
    lng: -0.1407,
    rating: 8,
    startTime: '16:00',
    endTime: '16:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A craft beer paradise with 10 cask ales and dozens of keg lines. Essential stop for beer lovers. One of the best pubs on the whole crawl.',
    website: 'https://www.caskpubandkitchen.com',
  },
  {
    id: 14,
    station: 'St James\'s Park',
    pubName: 'The Red Lion',
    address: '48 Parliament Street',
    postcode: 'SW1A 2NH',
    lat: 51.5012,
    lng: -0.1268,
    rating: 7,
    startTime: '16:30',
    endTime: '16:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Red Lion is a Westminster institution where MPs and civil servants have been drinking for centuries. The division bell still rings for Commons votes.',
    website: 'https://www.redlionwestminster.co.uk',
  },
  {
    id: 15,
    station: 'Westminster',
    pubName: 'St Stephen\'s Tavern',
    address: '10 Bridge Street',
    postcode: 'SW1A 2JR',
    lat: 51.5007,
    lng: -0.1246,
    rating: 8,
    startTime: '17:00',
    endTime: '17:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A magnificent Victorian pub opposite Big Ben with ornate glass and woodwork. Political history oozes from every corner. A must-visit.',
    website: 'https://www.ststephenstavern.co.uk',
  },
  {
    id: 16,
    station: 'Embankment',
    pubName: 'The Sherlock Holmes',
    address: '10 Northumberland Street',
    postcode: 'WC2N 5DB',
    lat: 51.5070,
    lng: -0.1235,
    rating: 7,
    startTime: '17:30',
    endTime: '17:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Sherlock Holmes is a themed pub with a recreation of Holmes\' study upstairs. Touristy but fun, and conveniently close to the station.',
    website: 'https://www.sherlockholmespub.com',
  },
  {
    id: 17,
    station: 'Temple',
    pubName: 'Temple Brew House',
    address: '46 Essex Street',
    postcode: 'WC2R 3JF',
    lat: 51.5118,
    lng: -0.1120,
    rating: 7,
    startTime: '18:00',
    endTime: '18:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'An independent brewpub on Essex Street with its own microbrewery in the basement. Open Saturdays until midnight — a rarity in this part of London. The house-brewed ales are worth trying, and it\'s right next door to Temple station.',
    website: 'https://www.templebrewhouse.com',
  },
  {
    id: 18,
    station: 'Blackfriars',
    pubName: 'The Blackfriar',
    address: '174 Queen Victoria Street',
    postcode: 'EC4V 4EG',
    lat: 51.5120,
    lng: -0.1035,
    rating: 9,
    startTime: '18:30',
    endTime: '18:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The most extraordinary pub interior in London. An Arts and Crafts masterpiece with marble walls and bronze friars. Nearly demolished in 1964 but saved by John Betjeman\'s campaign. Unmissable.',
    website: 'https://www.nicholsonspubs.co.uk/theblackfriarlondon',
  },
  {
    id: 19,
    station: 'Mansion House',
    pubName: 'Ye Olde Watling',
    address: '29 Watling Street',
    postcode: 'EC4M 9BR',
    lat: 51.5128,
    lng: -0.0936,
    rating: 7,
    startTime: '19:00',
    endTime: '19:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'Built in 1668 using timber from ships broken up after the Great Fire, Ye Olde Watling is one of the oldest pubs in the City. Open Saturdays noon to 8pm — check the time, as the crawl arrives around 7pm. A Nicholson\'s pub with good cask ales and a proper sense of history.',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/yeoldewatlingwatlingstreetlondon',
  },
  {
    id: 20,
    station: 'Cannon Street',
    pubName: 'The Hydrant',
    address: '1 Monument Street',
    postcode: 'EC3R 8BG',
    lat: 51.5104,
    lng: -0.0876,
    rating: 7,
    startTime: '19:30',
    endTime: '19:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Hydrant is a Fuller\'s pub on Monument Street, open Saturdays unlike most City pubs. A solid mid-crawl stop with a good range of ales and reliable food if you need refuelling for the final push.',
    website: 'https://www.thehydrant.co.uk',
  },
  {
    id: 21,
    station: 'Monument',
    pubName: 'The Monument',
    address: '18 Fish Street Hill',
    postcode: 'EC3R 6DB',
    lat: 51.5100,
    lng: -0.0860,
    rating: 7,
    startTime: '20:00',
    endTime: '20:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Monument pub sits right at the foot of the Monument to the Great Fire. A solid City pub with good views and a convenient location.',
    website: 'https://www.monumentpub.co.uk',
  },
  {
    id: 22,
    station: 'Tower Hill',
    pubName: 'The Hung Drawn and Quartered',
    address: '26-27 Great Tower Street',
    postcode: 'EC3R 5AQ',
    lat: 51.5100,
    lng: -0.0785,
    rating: 7,
    startTime: '20:30',
    endTime: '20:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Hung Drawn and Quartered is named after the gruesome fate of traitors at the nearby Tower. A large Fuller\'s pub with good food and views toward the Tower of London.',
    website: 'https://www.hung-drawn-and-quartered.co.uk',
  },
  {
    id: 23,
    station: 'Aldgate',
    pubName: 'The Hoop and Grapes',
    address: '47 Aldgate High Street',
    postcode: 'EC3N 1AL',
    lat: 51.5142,
    lng: -0.0758,
    rating: 8,
    startTime: '21:00',
    endTime: '21:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'One of the few timber-framed buildings to survive both the Great Fire and the Blitz. The crooked floors and leaning walls are part of the charm. Historic and atmospheric.',
    website: 'https://www.hoopandgrapes.co.uk',
  },
  {
    id: 24,
    station: 'Liverpool Street',
    pubName: 'Hamilton Hall',
    address: 'Liverpool Street Station',
    postcode: 'EC2M 7PY',
    lat: 51.5178,
    lng: -0.0823,
    rating: 8,
    startTime: '21:30',
    endTime: '21:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'A former ballroom inside Liverpool Street station with extraordinary gilded ceilings and baroque plasterwork. One of London\'s most spectacular pub interiors, inexplicably inside a train station.',
    website: 'https://www.jdwetherspoon.com',
  },
  {
    id: 25,
    station: 'Moorgate',
    pubName: 'The Globe',
    address: '83 Moorgate',
    postcode: 'EC2M 6SA',
    lat: 51.5182,
    lng: -0.0889,
    rating: 6,
    startTime: '22:00',
    endTime: '22:25',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Globe is a reliable City pub with a good range of ales. Not the most exciting stop but keeps the crawl moving through the northern City.',
  },
  {
    id: 26,
    station: 'Barbican',
    pubName: 'Fox & Anchor',
    address: '115 Charterhouse Street',
    postcode: 'EC1M 6AA',
    lat: 51.5199,
    lng: -0.1009,
    rating: 8,
    startTime: '22:30',
    endTime: '22:55',
    transportToNext: 'Circle Line',
    transportTime: 2,
    review: 'The Fox & Anchor is a beautifully restored Victorian pub on Charterhouse Street, open until 1am on Saturdays. The ornate tiled facade and etched glass interior are among the best-preserved in London. Famous for its full English breakfasts, though at this hour you\'re here for the ales. The penultimate stop — don\'t linger, Farringdon awaits.',
    website: 'https://www.foxandanchor.com',
  },
  {
    id: 27,
    station: 'Farringdon',
    pubName: 'The Holy Tavern',
    address: '55 Britton Street',
    postcode: 'EC1M 5UQ',
    lat: 51.5221,
    lng: -0.1049,
    rating: 9,
    startTime: '23:00',
    endTime: '23:25',
    transportToNext: null,
    transportTime: null,
    review: 'You made it. Formerly the Jerusalem Tavern, renamed in 2022 but otherwise unchanged — a tiny, perfectly preserved 18th-century pub still serving St Peter\'s ales from Suffolk. Last orders around 22:45, so don\'t dawdle at Barbican. 27 stations, 27 pubs, one legend.',
    website: 'https://theholytavern.com',
  },
];

// Calculate stats
export const circleLineStats = {
  totalPubs: circleLinePubs.length,
  totalStations: 27,
  estimatedTime: '13.5 hours',
  totalTubeTime: circleLinePubs.reduce((acc, pub) => acc + (pub.transportTime || 0), 0),
};
