export interface Crawl {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  pubs: number;
  duration: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Legendary';
  area: string;
  live: boolean;
  url?: string;
  accentColor: string;
}

export const crawls: Crawl[] = [
  {
    id: '1',
    slug: 'monopoly',
    name: 'Monopoly',
    tagline: 'Follow the board across London',
    description: 'Visit 26 pubs mapped to every property on the Monopoly board. From Old Kent Road to Mayfair.',
    pubs: 26,
    duration: '12 hours',
    difficulty: 'Legendary',
    area: 'Central London',
    live: true,
    url: 'https://monopolypubcrawl.com',
    accentColor: '#ef4444',
  },
  {
    id: '2',
    slug: 'jack-the-ripper',
    name: 'Jack the Ripper',
    tagline: 'Walk the dark streets of Victorian Whitechapel',
    description: 'Follow the trail through the historic pubs of the East End where Victorian London\'s darkest chapter unfolded.',
    pubs: 8,
    duration: '4 hours',
    difficulty: 'Medium',
    area: 'Whitechapel',
    live: false,
    accentColor: '#991b1b',
  },
  {
    id: '3',
    slug: 'beatles',
    name: 'Beatles',
    tagline: 'From Soho to Abbey Road',
    description: 'Visit the pubs where John, Paul, George and Ringo hung out during their London years.',
    pubs: 8,
    duration: '5 hours',
    difficulty: 'Easy',
    area: 'West End & St John\'s Wood',
    live: false,
    accentColor: '#f59e0b',
  },
  {
    id: '4',
    slug: 'circle-line',
    name: 'Circle Line',
    tagline: 'One stop, one pint, all the way round',
    description: 'A pub at every Circle Line station. Complete the loop before the Tube closes.',
    pubs: 27,
    duration: '10 hours',
    difficulty: 'Hard',
    area: 'Zone 1',
    live: false,
    accentColor: '#eab308',
  },
  {
    id: '5',
    slug: 'thames-path',
    name: 'Thames Path',
    tagline: 'Drink along London\'s greatest river',
    description: 'Follow the Thames from Tower Bridge to Westminster, stopping at the best riverside pubs.',
    pubs: 8,
    duration: '4 hours',
    difficulty: 'Easy',
    area: 'South Bank',
    live: false,
    accentColor: '#3b82f6',
  },
  {
    id: '6',
    slug: 'shakespeare',
    name: 'Shakespeare',
    tagline: 'Toast the Bard in Southwark\'s oldest pubs',
    description: 'Visit the taverns around the Globe Theatre where Shakespeare himself would have raised a tankard.',
    pubs: 7,
    duration: '4 hours',
    difficulty: 'Easy',
    area: 'Southwark',
    live: false,
    accentColor: '#a16207',
  },
  {
    id: '7',
    slug: 'criminal-london',
    name: 'Criminal London',
    tagline: 'The Krays, the heists, the boozers',
    description: 'Explore the pubs where London\'s most notorious criminals plotted, drank and met their fate.',
    pubs: 8,
    duration: '5 hours',
    difficulty: 'Medium',
    area: 'East End & Soho',
    live: false,
    accentColor: '#52525b',
  },
  {
    id: '8',
    slug: 'ww2',
    name: 'WW2',
    tagline: 'Pubs that survived the Blitz',
    description: 'Visit the pubs that kept spirits high through the darkest days. Stories of resilience and courage.',
    pubs: 8,
    duration: '4 hours',
    difficulty: 'Easy',
    area: 'City & Westminster',
    live: false,
    accentColor: '#57534e',
  },
  {
    id: '9',
    slug: 'david-bowie',
    name: 'David Bowie',
    tagline: 'Ziggy drank here',
    description: 'From Brixton to the West End, drink in the pubs and haunts of the Starman himself.',
    pubs: 7,
    duration: '5 hours',
    difficulty: 'Medium',
    area: 'Brixton & Soho',
    live: false,
    accentColor: '#ec4899',
  },
  {
    id: '10',
    slug: 'rolling-stones',
    name: 'Rolling Stones',
    tagline: 'Start me up in Chelsea',
    description: 'Follow Mick and Keith through the pubs of Richmond, Chelsea and Soho where the Stones got their start.',
    pubs: 8,
    duration: '5 hours',
    difficulty: 'Medium',
    area: 'Chelsea & Richmond',
    live: false,
    accentColor: '#dc2626',
  },
  {
    id: '11',
    slug: 'bermondsey-beer-mile',
    name: 'Bermondsey Beer Mile',
    tagline: 'London\'s craft beer capital',
    description: 'Tour the famous railway arch breweries of Bermondsey. Over a dozen craft breweries in one glorious mile.',
    pubs: 12,
    duration: '6 hours',
    difficulty: 'Medium',
    area: 'Bermondsey',
    live: false,
    accentColor: '#d97706',
  },
  {
    id: '12',
    slug: 'royal-family',
    name: 'Royal Family',
    tagline: 'Drink like a royal',
    description: 'Visit the pubs with royal connections, from historic royal warrants to where princes have been spotted.',
    pubs: 7,
    duration: '4 hours',
    difficulty: 'Easy',
    area: 'Mayfair & Westminster',
    live: false,
    accentColor: '#7c3aed',
  },
];
