// Monopoly Pub Crawl - All 26 board properties mapped to real London pubs
// Route follows the optimised crawl order from the original monopolypubcrawl.com

import { BasePub } from './types';

export interface MonopolyPub extends BasePub {
  property: string;
  rating: number;
  startTime: string;
  endTime: string;
  transportToNext: string | null;
  transportTime: number | null;
  price: number;
  pintQuantity: string;
  color: string;
  colorGroup: string;
}

export const monopolyPubs: MonopolyPub[] = [
  {
    id: 1,
    property: "Old Kent Road",
    pubName: "Lord Nelson",
    address: "386 Old Kent Rd",
    postcode: "SE1 5AA",
    lat: 51.4842,
    lng: -0.0720,
    rating: 6,
    startTime: "11:00",
    endTime: "11:05",
    transportToNext: "Cycle",
    transportTime: 13,
    price: 2.60,
    pintQuantity: "1/2",
    review: 'One of two pubs left on Old Kent Road \u2014 a street that once had 39. The Lord Nelson is Grade II listed and on CAMRA\'s National Inventory, which means the Victorian interior is the real deal: a massive gilded mirror depicting Admiral Nelson at the Battle of Cape Vincent in 1797, made by James Carter of Gray\'s Inn Road around 1888, and an impressive timber arcade across the servery. It opens at 11am, and you\'ll want to be in and out quickly to bank time for later. Other Monopoly groups will be starting here too \u2014 say hello, you\'ll be leapfrogging each other all day. Get a photo under the Old Kent Road sign, then grab a Lime bike for the ride across Tower Bridge.',
    color: "#8B4513",
    colorGroup: "brown",
    image: "/pubs/monopoly/lord-nelson.jpeg",
    website: 'https://www.lordnelsonsouthwark.com',
  },
  {
    id: 2,
    property: "Fenchurch St Station",
    pubName: "The Minories",
    address: "64-73 Minories",
    postcode: "EC3N 1LA",
    lat: 51.5117,
    lng: -0.0756,
    rating: 7,
    startTime: "11:18",
    endTime: "11:38",
    transportToNext: "Walk",
    transportTime: 4,
    price: 7.20,
    pintQuantity: "1",
    review: 'Built into the arches beneath the Fenchurch Street railway viaduct, The Minories may occupy part of the former Minories station, which closed in 1873. The street itself takes its name from the Minoresses \u2014 an order of nuns who established an abbey outside the City walls in 1293. Inside, the vaulted brick ceiling and flagstone floor give it the feel of a crypt that serves lager. It\'s dark, which works better in winter than summer, but there\'s a beer garden out back if you need daylight. First station on the route \u2014 settle in, because the pace picks up from here.',
    color: "#000000",
    colorGroup: "station",
    website: "https://www.theminoriespub.co.uk",
    image: "/pubs/monopoly/the-minories.jpeg",
  },
  {
    id: 3,
    property: "Whitechapel Road",
    pubName: "The Hoop and Grapes",
    address: "47 Aldgate High St",
    postcode: "EC3N 1AL",
    lat: 51.5138,
    lng: -0.0762,
    rating: 5,
    startTime: "11:42",
    endTime: "12:02",
    transportToNext: "Walk",
    transportTime: 9,
    price: 3.70,
    pintQuantity: "1/2",
    review: 'The Great Fire of 1666 stopped about 50 yards short of this building. The Hoop and Grapes is one of the last timber-framed structures in the City of London, probably built in the late 17th century, though the site has been licensed since 1593 under at least four different names \u2014 The Castle, the Angel & Crown, Christopher Hills, and finally Hoop and Grapes in the 1920s. The front of the building leans visibly outward, saved from collapse by extensive restoration work. Inside, the floors are off-kilter and the beams are twisted. You can stand out front on Aldgate High Street if the light is better out there than in.',
    color: "#8B4513",
    colorGroup: "brown",
    website: "https://www.nicholsonspubs.co.uk/restaurants/london/thehoopandgrapesaldgatecityoflondon",
    image: "/pubs/monopoly/hoop-and-grapes.jpeg",
  },
  {
    id: 4,
    property: "Liverpool St Station",
    pubName: "Hamilton Hall",
    address: "Liverpool St",
    postcode: "EC2M 7PY",
    lat: 51.5179,
    lng: -0.0828,
    rating: 4.5,
    startTime: "12:11",
    endTime: "12:31",
    transportToNext: "Tube",
    transportTime: 24,
    price: 6.52,
    pintQuantity: "1",
    review: 'The second station takes you into the old Great Eastern Hotel ballroom \u2014 now a Wetherspoons, which makes it a genuinely surreal place to have a midday pint. Hamilton Hall is named after Lord Claud Hamilton, chairman of the Great Eastern Railway from 1893 to 1923, and the interior was redesigned in 1901 to mimic the Palais Soubise in Paris. Ornate plaster ceilings, painted panels, a decorative mezzanine where the hotel orchestra once played. It became Wetherspoons\' first-ever station pub in 1991. From here, walk round to Moorgate and jump on the Northern line northbound to Angel. Good moment to grab a meal deal \u2014 the pace picks up after this one.',
    color: "#000000",
    colorGroup: "station",
    website: "https://www.jdwetherspoon.com/pubs/all-pubs/england/london/hamilton-hall-london",
    image: "/pubs/monopoly/hamilton-hall.jpeg",
  },
  {
    id: 5,
    property: "The Angel, Islington",
    pubName: "Camden Head",
    address: "2 Camden Walk",
    postcode: "N1 8DY",
    lat: 51.5360,
    lng: -0.1050,
    rating: 9,
    startTime: "12:55",
    endTime: "13:15",
    transportToNext: "Walk",
    transportTime: 8,
    price: 3.08,
    pintQuantity: "1/2",
    review: 'After getting off the Tube at Angel, head to this courtyard pub just off Camden Passage. Camden Head dates from 1899 \u2014 carved panels on the external stacks confirm it \u2014 and enough of the original gin palace survives inside: etched glass partitions, ornate lamps. Downstairs hosts Angel Comedy Club, which has seen Alan Carr, Stephen Merchant, and Bob Mortimer on the mic over the years. We normally have a pint here rather than a half, partly because the beer garden is worth lingering in, partly because it kicks off the best stretch of the crawl. If you can get Estrella Galicia on tap, do.',
    color: "#87CEEB",
    colorGroup: "lightBlue",
    website: "https://www.greeneking-pubs.co.uk/pubs/greater-london/camden-head",
    image: "/pubs/monopoly/camden-head.jpeg",
  },
  {
    id: 6,
    property: "Pentonville Road",
    pubName: "The Castle",
    address: "Pentonville Road",
    postcode: "N1 9HF",
    lat: 51.5318,
    lng: -0.1130,
    rating: 9.5,
    startTime: "13:23",
    endTime: "13:43",
    transportToNext: "Walk",
    transportTime: 15,
    price: 3.85,
    pintQuantity: "1/2",
    review: 'Our favourite pub on the entire crawl. Make sure you head up to the terrace \u2014 the sun on the rooftop here can feel like you\'ve teleported to southern Europe. The Hatton Garden heist of Easter weekend 2015 was planned at this pub: Brian Reader, Terry Perkins, Kenny Collins and five other regulars, mostly in their sixties and seventies, held planning meetings in a quiet corner for three years. After the robbery they sat here and congratulated themselves \u2014 by which point the police had the pub under surveillance, with cameras and lip-readers. There\'s a blue plaque inside. The first of the longer walks starts from here, about fifteen minutes to King\'s Cross.',
    color: "#87CEEB",
    colorGroup: "lightBlue",
    website: "https://www.thecastleislington.co.uk",
    image: "/pubs/monopoly/the-castle.jpeg",
  },
  {
    id: 7,
    property: "Kings Cross Station",
    pubName: "The Parcel Yard",
    address: "Kings Cross Station",
    postcode: "N1C 4AH",
    lat: 51.5320,
    lng: -0.1240,
    rating: 6.5,
    startTime: "13:58",
    endTime: "14:18",
    transportToNext: "Walk",
    transportTime: 11,
    price: 7.05,
    pintQuantity: "1",
    review: 'A Fuller\'s pub set in the old 1852 Great Northern Railway parcel sorting office above King\'s Cross station. The Parcel Yard isn\'t the easiest to find \u2014 you need to be inside the station and head up the stairs towards the back. Once you do, you\'ll find a double-height atrium with original features from its freight-handling days, plus a solid Fuller\'s lineup including ESB and Bengal Lancer. Platform 9 3/4 is nearby for any Harry Potter fans on the crawl, but there isn\'t much time to lose. Prince Charles visited once, apparently. We were not there for that.',
    color: "#000000",
    colorGroup: "station",
    website: "https://www.parcelyard.co.uk",
    image: "/pubs/monopoly/parcel-yard.jpeg",
  },
  {
    id: 8,
    property: "Euston Road",
    pubName: "The Euston Tap",
    address: "Euston Station",
    postcode: "NW1 2EF",
    lat: 51.5282,
    lng: -0.1337,
    rating: 8,
    startTime: "14:29",
    endTime: "14:49",
    transportToNext: "Walk",
    transportTime: 18,
    price: 3.25,
    pintQuantity: "1/2",
    review: 'The light blues aren\'t the most coveted set on the Monopoly board, but they\'re comfortably the best colour on the crawl. The Euston Tap is housed in one of two Portland stone lodges at the front of Euston station, built around 1870 and engraved with the names of towns served by the railway. They\'re the last remnants of the old Euston station, torn down in the 1960s despite John Betjeman\'s lobbying \u2014 the demolished Euston Arch features in the pub\'s logo. Over 30 rotating keg lines plus cask, crammed into a compact space. One of London\'s finest beer bars. Don\'t rush this one.',
    color: "#87CEEB",
    colorGroup: "lightBlue",
    website: "https://www.eustontap.com",
    image: "/pubs/monopoly/euston-tap.jpeg",
  },
  {
    id: 9,
    property: "Marylebone Station",
    pubName: "The Marylebone",
    address: "93 Marylebone High St",
    postcode: "W1U 4RE",
    lat: 51.5210,
    lng: -0.1520,
    rating: 7,
    startTime: "15:07",
    endTime: "15:27",
    transportToNext: "Walk",
    transportTime: 18,
    price: 7.20,
    pintQuantity: "1",
    review: 'At the end of the longest walk on the crawl \u2014 about eighteen minutes \u2014 you\'ll arrive at the fourth and final station. There\'s been a pub on this site since 1863, when it was the Queen\'s Head. The Marylebone is now a cocktail-leaning bar on one of London\'s better high streets, and the village-like feel of the area is a welcome change of pace after three train stations. It\'s often full inside but there\'s room to stand on the street with a drink. Hunger usually sets in around here as a result of the walking. Pick up food on the way to the next one \u2014 you won\'t regret it.',
    color: "#000000",
    colorGroup: "station",
    website: "https://www.themarylebone.co.uk",
    image: "/pubs/monopoly/the-marylebone.jpeg",
  },
  {
    id: 10,
    property: "Park Lane",
    pubName: "The Audley",
    address: "41-43 Mount St",
    postcode: "W1K 2RX",
    lat: 51.5098,
    lng: -0.1520,
    rating: 7,
    startTime: "15:45",
    endTime: "16:05",
    transportToNext: "Walk",
    transportTime: 9,
    price: 4.50,
    pintQuantity: "1/2",
    review: 'First licensed in 1730 as the Bricklayers Arms, rebuilt in 1889 by James Watney & Co to designs by Thomas Verity \u2014 the same architect who did the exterior of the pavilion at Lord\'s. The first Duke of Westminster insisted it be renamed the Audley Hotel as a condition of the rebuild. It\'s Grade II listed, all red brick and pink terracotta outside, polished wood and plasterwork inside. Look for the original double-faced clock and the wooden fireplace inscribed with the Latin \u201csalve.\u201d The Swiss art dealers Iwan and Manuela Wirth took over the lease and commissioned a ceiling work by the late Dame Phyllida Barlow. Pints are not cheap. You are in Mayfair.',
    color: "#00008B",
    colorGroup: "darkBlue",
    website: "https://the-audley.com",
    image: "/pubs/monopoly/the-audley.jpeg",
  },
  {
    id: 11,
    property: "Mayfair",
    pubName: "The Burlington Arms",
    address: "21 Old Burlington St",
    postcode: "W1S 2JL",
    lat: 51.5105,
    lng: -0.1395,
    rating: 8,
    startTime: "16:14",
    endTime: "16:34",
    transportToNext: "Walk",
    transportTime: 12,
    price: 3.75,
    pintQuantity: "1/2",
    review: 'Licensed in 1720 as the Coach & Horses, rebuilt in 1783, and again in 1882 at a cost of \u00a31,789. The Burlington Arms sits on a quiet side street between Savile Row and Bond Street, facing the rear of the old Savile Row police station. It\'s split over two floors \u2014 main bar on the ground, restaurant-slash-function-room upstairs. A smallish pub, which at this point in the crawl is fine because you don\'t need a sprawling venue, you need a half-pint and a seat. Four changing cask ales. After this one, the dark blues are done and you\'re heading into the belly of the beast.',
    color: "#00008B",
    colorGroup: "darkBlue",
    website: "https://www.burlingtonarms.com",
    image: "/pubs/monopoly/burlington-arms.jpeg",
  },
  {
    id: 12,
    property: "Piccadilly",
    pubName: "St James's Tavern",
    address: "45 Great Windmill St",
    postcode: "W1D 7NE",
    lat: 51.5112,
    lng: -0.1340,
    rating: 6,
    startTime: "16:46",
    endTime: "17:06",
    transportToNext: "Walk",
    transportTime: 7,
    price: 4.05,
    pintQuantity: "1/2",
    review: 'A pub has stood on this site since 1733, when it was called the Catherine Wheel. The current building went up in 1897 to the designs of William Brutton, a prolific pub architect, at a cost of \u00a34,860. Look for the Doulton tile paintings \u2014 Shakespearean scenes made by Doulton\'s of Lambeth, plus two panels showing hops and a vine. St James\'s Tavern sits right where Soho meets the West End, and the pavement outside feels like it\'s moving at double speed. There\'s a McDonald\'s across the road, which by pub twelve may be the most important sentence in this guide.',
    color: "#FFD700",
    colorGroup: "yellow",
    website: "https://www.nicholsonspubs.co.uk/restaurants/london/thestjamestavernwestminster",
    image: "/pubs/monopoly/st-james-tavern.jpeg",
  },
  {
    id: 13,
    property: "Pall Mall",
    pubName: "The Red Lion",
    address: "Crown Passage",
    postcode: "SW1Y 6PP",
    lat: 51.5068,
    lng: -0.1379,
    rating: 6,
    startTime: "17:13",
    endTime: "17:33",
    transportToNext: "Walk",
    transportTime: 11,
    price: 3.70,
    pintQuantity: "1/2",
    review: 'Down a narrow alley off Pall Mall, The Red Lion claims the second oldest beer licence in London. The current building dates from 1861, though the pub\'s been here in some form for about 400 years. Legend has it Charles II used to meet Nell Gwyn here via a tunnel running beneath Crown Passage \u2014 sceptics have looked and found nothing, but it\'s a good story. The interior fittings are 1930s. Walking in here from the West End traffic is a genuine gear change, and it marks the halfway point of the crawl. The second half is what separates completion from capitulation.',
    color: "#FF69B4",
    colorGroup: "pink",
    website: "https://www.redlionwestminster.co.uk",
    image: "/pubs/monopoly/red-lion.jpeg",
  },
  {
    id: 14,
    property: "Whitehall",
    pubName: "Silver Cross",
    address: "33 Whitehall",
    postcode: "SW1A 2BX",
    lat: 51.5065,
    lng: -0.1254,
    rating: 5.5,
    startTime: "17:44",
    endTime: "18:04",
    transportToNext: "Walk",
    transportTime: 1,
    price: 2.85,
    pintQuantity: "1/2",
    review: 'First licensed in 1674 as The Garter, but the building goes back further \u2014 part of the site was St Katherine\'s Hermitage, constructed in the thirteenth century. The Silver Cross sits on Whitehall, and its most-repeated fact is that Charles I granted it a licence to operate as a brothel, which the BBC claimed in 1999 was technically never revoked, making it the only legal brothel in the country. It\'s now a Greene King. The plaster ceiling in the bar dates from Charles I\'s time in Whitehall Palace. From here it\'s a one-minute walk to the next pub, which at this stage of the crawl feels like a gift.',
    color: "#FF69B4",
    colorGroup: "pink",
    website: "https://www.greeneking.co.uk/pubs/greater-london/silver-cross",
    image: "/pubs/monopoly/silver-cross.jpeg",
  },
  {
    id: 15,
    property: "Northumberland Avenue",
    pubName: "The Ship & Shovell",
    address: "2 Craven Passage",
    postcode: "WC2N 5NF",
    lat: 51.5076,
    lng: -0.1235,
    rating: 6,
    startTime: "18:05",
    endTime: "18:25",
    transportToNext: "Walk",
    transportTime: 20,
    price: 3.80,
    pintQuantity: "1/2",
    review: 'London\'s only pub split across both sides of a street. The Ship & Shovell is two separate bars divided by Craven Passage and connected underground by a shared cellar \u2014 until 1998 they were actually two separate pubs, The Ship and The Shovell, until the cellars were joined by a tunnel containing the kitchen. The buildings date from 1731-33 and have been Grade II listed since 1970. Named after Admiral Sir Cloudesley Shovell, who rose from cabin boy to Admiral of the Fleet before dying in a shipwreck off the Scilly Isles. People congregate all the way up the alley. From here, the last of the bigger walks \u2014 about seventeen minutes to Fleet Street.',
    color: "#FF69B4",
    colorGroup: "pink",
    website: "https://www.shipandshovell.co.uk",
    image: "/pubs/monopoly/ship-and-shovell.jpeg",
  },
  {
    id: 16,
    property: "Fleet Street",
    pubName: "Ye Olde Cheshire Cheese",
    address: "145 Fleet St",
    postcode: "EC4A 2BP",
    lat: 51.5141,
    lng: -0.1081,
    rating: 5,
    startTime: "18:45",
    endTime: "19:05",
    transportToNext: "Walk",
    transportTime: 10,
    price: 3.60,
    pintQuantity: "1/2",
    review: 'Rebuilt in 1667 after the Great Fire, though a pub has been on this site since 1538 and the cellars may date to a 13th-century Carmelite monastery. Samuel Johnson lived round the corner at 17 Gough Square \u2014 whether he actually drank here is debated, but Dickens, Mark Twain, and W.B. Yeats definitely did. Dickens featured it in A Tale of Two Cities. The interior is a warren of rooms connected by narrow staircases: the Chop Room, the Cellar Bar, the Johnson Bar, the Williams Room. You enter through a narrow passage off Fleet Street and the 21st century disappears. Arguably the most historically significant pub on the crawl. Do not skip this one.',
    color: "#FF0000",
    colorGroup: "red",
    website: "https://www.ye-olde-cheshire-cheese.co.uk",
    image: "/pubs/monopoly/cheshire-cheese.jpeg",
  },
  {
    id: 17,
    property: "Strand",
    pubName: "The Wellington",
    address: "351 Strand",
    postcode: "WC2R 0HS",
    lat: 51.5107,
    lng: -0.1195,
    rating: 6,
    startTime: "19:15",
    endTime: "19:35",
    transportToNext: "Walk",
    transportTime: 3,
    price: 4.05,
    pintQuantity: "1",
    review: 'Built in 1903, The Wellington has neo-gothic interiors worth looking up at \u2014 a sculpted ceiling, stained glass windows, and an original marble fireplace. It\'s named after the Duke, sits next door to the Lyceum Theatre, and was last refurbished in 2023. There\'s a Tesco en route here from Ye Olde Cheshire Cheese, which is useful intelligence at this point in the day. The outdoor seating along the Wellington Street frontage is a decent spot to sit and watch Covent Garden go by. Upstairs there\'s a larger, more comfortable bar if you want to briefly pretend you\'re not on a twelve-hour pub crawl.',
    color: "#FF0000",
    colorGroup: "red",
    website: "https://www.thewellingtonpub.com",
    image: "/pubs/monopoly/the-wellington.jpeg",
  },
  {
    id: 18,
    property: "Bow Street",
    pubName: "The Marquess of Anglesey",
    address: "39 Bow St",
    postcode: "WC2E 7AU",
    lat: 51.5130,
    lng: -0.1222,
    rating: 8.5,
    startTime: "19:38",
    endTime: "19:58",
    transportToNext: "Walk",
    transportTime: 9,
    price: 3.85,
    pintQuantity: "1/2",
    review: 'Built on the site of Edward Miles\' coffee house \u2014 one of the first in London, dating from 1663. Licensed as a pub since 1752, first as the Barley Mow, then the Green Man, before being renamed after the Marquess of Anglesey, who lost a leg to one of the last cannon shots at Waterloo. A Young\'s pub right next to the Royal Opera House. The rooftop terrace is the standout feature \u2014 retractable roof, views across theatreland. WWII shrapnel damage is still visible on the exterior if you look. Try not to fall over on the terrace; a member of our group who shall remain unnamed has done exactly this.',
    color: "#FF4500",
    colorGroup: "orange",
    website: "https://www.themarquessofanglesey.co.uk",
    image: "/pubs/monopoly/marquess-of-anglesey.jpeg",
  },
  {
    id: 19,
    property: "Trafalgar Square",
    pubName: "The Admiralty",
    address: "66 Trafalgar Sq",
    postcode: "WC2N 5DS",
    lat: 51.5080,
    lng: -0.1270,
    rating: 7,
    startTime: "20:07",
    endTime: "20:27",
    transportToNext: "Walk",
    transportTime: 5,
    price: 4.10,
    pintQuantity: "1/2",
    review: 'This is where the memory begins to get a little hazy. The Admiralty sits right on Trafalgar Square in a Grade II listed building from 1871, originally built as the Union Bank to designs by F.W. Porter. It was a NatWest branch, then a Scottish restaurant, before Fuller\'s converted it in 2014 \u2014 opening two days after Trafalgar Day, with Admiral Lord West performing the honours. The downstairs Gundeck bar has semi-private booths modelled on HMS Victory\'s lower deck. Nelson\'s Column looms through the windows. After a basement fire in 2022, it reopened in April 2023.',
    color: "#FF0000",
    colorGroup: "red",
    website: "https://www.admiraltytrafalgar.co.uk",
    image: "/pubs/monopoly/the-admiralty.jpeg",
  },
  {
    id: 20,
    property: "Leicester Square",
    pubName: "The Moon Under Water",
    address: "28 Leicester Square",
    postcode: "WC2H 7LE",
    lat: 51.5113,
    lng: -0.1302,
    rating: 5,
    startTime: "20:32",
    endTime: "20:52",
    transportToNext: "Walk",
    transportTime: 3,
    price: 3.50,
    pintQuantity: "1/2",
    review: 'Named after George Orwell\'s 1946 essay in the Evening Standard describing his ideal pub \u2014 Victorian architecture, barmaids who know your name, quiet enough to have a conversation. The irony of a Wetherspoons carrying the name is not lost on anyone. This particular Moon Under Water takes up a huge space on Leicester Square, right next to the Odeon. The prices are the cheapest you\'ll see all day, which at pub twenty is not nothing. Don\'t linger \u2014 get in, get the half, get out. You have six to go.',
    color: "#FFD700",
    colorGroup: "yellow",
    website: "https://www.jdwetherspoon.com/pubs/all-pubs/england/london/the-moon-under-water-leicester-square",
    image: "/pubs/monopoly/moon-under-water.jpeg",
  },
  {
    id: 21,
    property: "Coventry Street",
    pubName: "The Coach House",
    address: "7 Oxendon St",
    postcode: "SW1Y 4EE",
    lat: 51.5095,
    lng: -0.1310,
    rating: 6.5,
    startTime: "20:55",
    endTime: "21:15",
    transportToNext: "Walk",
    transportTime: 7,
    price: 3.90,
    pintQuantity: "1",
    review: 'Originally No.7 Piano Bar, then The Comedy, now The Coach House \u2014 renamed to nod to the area\'s Regency-era history as a staging post for coach travel. It\'s a four-storey pub on Oxendon Street, just off Coventry Street, and the upper floors host the Piccadilly Comedy Club on Friday and Saturday nights. At this stage of the crawl, the fact that it\'s an escape from the West End pavement chaos is its main virtue. Five pubs to go. Keep moving.',
    color: "#FFD700",
    colorGroup: "yellow",
    website: "https://www.thecoachhousesoho.co.uk",
    image: "/pubs/monopoly/coach-house.jpeg",
  },
  {
    id: 22,
    property: "Regent Street",
    pubName: "The Starman",
    address: "15 Heddon St",
    postcode: "W1B 4BF",
    lat: 51.5125,
    lng: -0.1395,
    rating: 6,
    startTime: "21:22",
    endTime: "21:42",
    transportToNext: "Walk",
    transportTime: 2,
    price: 3.80,
    pintQuantity: "1/2",
    review: 'The Ziggy Stardust album cover was shot at 23 Heddon Street on 13 January 1972 \u2014 Bowie, ill with flu, stepped outside into the rain and stood under the sign of K. West, a furrier whose directors were not pleased about appearing on a pop album. The Starman bar opened a few doors down in 2022 and has recreated the K. West sign in the basement. There\'s a Crown Estate commemorative plaque at No. 23 where the original sign was. Check it out on the way in. The bar itself is modern, stylish, and the Bowie connection gives it more character than most of the late-crawl stops.',
    color: "#228B22",
    colorGroup: "green",
    website: "https://www.thestarman.co.uk",
    image: "/pubs/monopoly/starman.jpeg",
  },
  {
    id: 23,
    property: "Vine Street",
    pubName: "Leicester Arms",
    address: "44 Glasshouse St",
    postcode: "W1B 5DP",
    lat: 51.5108,
    lng: -0.1360,
    rating: 6.5,
    startTime: "21:44",
    endTime: "22:04",
    transportToNext: "Walk",
    transportTime: 5,
    price: 3.80,
    pintQuantity: "1/2",
    review: 'Vine Street doesn\'t really exist anymore \u2014 21 metres of dead end, the shortest street on the Monopoly board. The Leicester Arms on Glasshouse Street is the closest pub to where Vine Street once ran. First licensed in 1725 as the Harp, rebuilt in 1892, it picked up its current name in 1927 when it was transferred from the Leicester Lounge on New Coventry Street. It\'s a single-bar corner pub. At pub twenty-three, you are not here for the architecture. You are here because the board says so. Water. Drink water.',
    color: "#FF4500",
    colorGroup: "orange",
    website: "https://www.leicesterarmspub.co.uk",
    image: "/pubs/monopoly/leicester-arms.jpeg",
  },
  {
    id: 24,
    property: "Marlborough Street",
    pubName: "Shakespeare's Head",
    address: "29 Great Marlborough St",
    postcode: "W1F 7HZ",
    lat: 51.5140,
    lng: -0.1385,
    rating: 7,
    startTime: "22:09",
    endTime: "22:29",
    transportToNext: "Walk",
    transportTime: 6,
    price: 3.32,
    pintQuantity: "1",
    review: 'Built in 1735 by Thomas and John Shakespeare \u2014 genuinely distant relatives of the playwright. The pub sign is a reproduction of Martin Droeshout\'s portrait of Shakespeare, and there\'s a life-size bust of the poet on the building\'s exterior, gazing down at Great Marlborough Street. One of the bust\'s hands is missing, knocked off by a bomb during the Second World War. Shakespeare\'s Head is a Greene King, a couple of hundred feet from Carnaby Street, and the outdoor seating is a reasonable place to sit and watch the last hour of daylight if you\'ve got any left. Three to go.',
    color: "#FF4500",
    colorGroup: "orange",
    website: "https://www.greeneking-pubs.co.uk/pubs/greater-london/shakespeares-head",
    image: "/pubs/monopoly/shakespeares-head.jpeg",
  },
  {
    id: 25,
    property: "Bond Street",
    pubName: "Duke of York",
    address: "Dering St, New Bond St",
    postcode: "W1S 1AF",
    lat: 51.5140,
    lng: -0.1460,
    rating: 6,
    startTime: "22:35",
    endTime: "22:55",
    transportToNext: "Walk",
    transportTime: 2,
    price: 3.80,
    pintQuantity: "1/2",
    review: 'First licensed in 1722 as the Shepherd & Flock \u2014 named after the street\'s original name, Shepherd Street \u2014 before becoming the Duke of York in 1806 and being rebuilt in 1886. It\'s a corner pub on three levels connected by a central spiral staircase, sitting on a quiet street just off Bond Street. At this point in the crawl, the strict timings throughout the day either pay off or they don\'t. If you\'re here on schedule, you\'re going to finish. If you\'re behind, you\'re racing the clock. One more stop.',
    color: "#228B22",
    colorGroup: "green",
    image: "/pubs/monopoly/duke-of-york.jpeg",
    website: 'https://www.greeneking.co.uk/pubs/greater-london/duke-of-york',
  },
  {
    id: 26,
    property: "Oxford Street",
    pubName: "The Duchess",
    address: "Woodcock St",
    postcode: "W1C 2AD",
    lat: 51.5148,
    lng: -0.1505,
    rating: 6,
    startTime: "22:57",
    endTime: "23:17",
    transportToNext: null,
    transportTime: null,
    price: 7.35,
    pintQuantity: "1",
    review: 'The grand finale. A pub has been on this site since 1765, but at 11pm on 6 December 1944, a V2 missile destroyed the then-Red Lion, killing eighteen people and injuring around forty. The building was rebuilt in 1958 and went through several names \u2014 Henry Holland, after the Georgian architect \u2014 before becoming The Duchess in 2022, a nod to the BBC drama The Duchess of Duke Street. It sits opposite the Duke Street entrance to Selfridges, high-ceilinged and wood-panelled. It closes at midnight, which gives you breathing room. If you\'ve made it here, you\'ve done all 26. We can say from experience that the urge to continue to Soho afterwards is considerably weaker than you\'d expect.',
    color: "#228B22",
    colorGroup: "green",
    website: "https://www.theduchessw1.co.uk",
    image: "/pubs/monopoly/the-duchess.jpeg",
  }
];

// Monopoly color group definitions
export const monopolyColorGroups: Record<string, { name: string; color: string; bg: string }> = {
  brown: { name: "Brown", color: "#8B4513", bg: "#F5E6D3" },
  lightBlue: { name: "Light Blue", color: "#87CEEB", bg: "#E8F4FD" },
  pink: { name: "Pink", color: "#D63384", bg: "#FCE4EC" },
  orange: { name: "Orange", color: "#FF6B00", bg: "#FFF3E0" },
  red: { name: "Red", color: "#D32F2F", bg: "#FFEBEE" },
  yellow: { name: "Yellow", color: "#FFD600", bg: "#FFFDE7" },
  green: { name: "Green", color: "#2E7D32", bg: "#E8F5E9" },
  darkBlue: { name: "Dark Blue", color: "#1A237E", bg: "#E8EAF6" },
  station: { name: "Station", color: "#212121", bg: "#F5F5F5" }
};

// Calculate totals
export const monopolyStats = {
  totalPubs: monopolyPubs.length,
  totalPints: monopolyPubs.reduce((sum, p) => sum + (p.pintQuantity === '1' ? 1 : 0.5), 0),
  totalCost: monopolyPubs.reduce((sum, p) => sum + p.price, 0),
  totalWalkingMins: monopolyPubs.reduce((sum, p) => sum + (p.transportTime || 0), 0),
};
