import { BasePub } from './types';

export interface SouthBankPub extends BasePub {
  landmark: string;
  walkToNext: string | null;
  bonus: boolean;
}

export const southBankPubs: SouthBankPub[] = [
  {
    id: 1,
    pubName: 'The Black Friar',
    address: '174 Queen Victoria Street',
    postcode: 'EC4V 4EG',
    lat: 51.5121,
    lng: -0.1037,
    landmark: 'Blackfriars Bridge',
    bonus: false,
    review: 'The Black Friar sits at the north end of Blackfriars Bridge — technically not the South Bank, but it\'s two minutes\' walk from the river and the best possible way to start a Thames crawl. Built in 1875 on the site of a 13th-century Dominican priory, the interior was transformed in 1905 into London\'s finest example of Arts and Crafts pub design. Mosaics, marble, bronze reliefs of jolly monks on every surface. John Betjeman saved it from demolition in the 1960s.',
    walkToNext: 'Cross Blackfriars Bridge, 5 min walk',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/theblackfriarblackfriars',
  },
  {
    id: 2,
    pubName: 'Doggett\'s Coat and Badge',
    address: '1 Blackfriars Bridge',
    postcode: 'SE1 9UD',
    lat: 51.5084,
    lng: -0.1048,
    landmark: 'South end of Blackfriars Bridge',
    bonus: false,
    review: 'Doggett\'s Coat and Badge is named after Thomas Doggett, the 18th-century actor who organised the London Bridge to Chelsea rowing race in 1715 — said to be the oldest continuous sporting event in the UK. A large Nicholson\'s pub spread over four floors at the south end of Blackfriars Bridge, with 10 handpumps and a river terrace stacked with views. The building is post-war concrete that gives little away from outside — inside it\'s much bigger than you\'d expect.',
    walkToNext: '8 min walk east along the river',
    website: 'https://www.doggettscoatandbadge.co.uk',
  },
  {
    id: 3,
    pubName: 'Founders Arms',
    address: '52 Hopton Street',
    postcode: 'SE1 9JH',
    lat: 51.5085,
    lng: -0.1019,
    landmark: 'St Paul\'s Cathedral view',
    bonus: false,
    review: 'The Founders Arms is a modern pub with no historical interest and no pretence otherwise. You\'re here for the view — St Paul\'s Cathedral framed perfectly across the river from the terrace. On a clear day it\'s one of the best pub views in London. A good place to settle in with the first proper pint of the crawl.',
    walkToNext: '5 min walk east past Tate Modern',
    website: 'https://www.foundersarms.co.uk',
  },
  {
    id: 4,
    pubName: 'The Anchor Bankside',
    address: '34 Park Street',
    postcode: 'SE1 9EF',
    lat: 51.5068,
    lng: -0.0931,
    landmark: 'Shakespeare\'s Globe',
    bonus: false,
    review: 'The Anchor Bankside has had a pub on this site since at least the early 1600s, when Bankside was London\'s red-light entertainment district — theatres, bear pits, and brothels shoulder to shoulder. Samuel Pepys is said to have watched the Great Fire of London from here on 2 September 1666. The current building is 18th century. Shakespeare\'s Globe is next door.',
    walkToNext: '5 min walk east via Clink Street',
    website: 'https://www.greeneking-pubs.co.uk/pubs/southwark/anchor-bankside',
  },
  {
    id: 5,
    pubName: 'The Mudlark',
    address: '4 Montague Close',
    postcode: 'SE1 9DA',
    lat: 51.5065,
    lng: -0.0890,
    landmark: 'London Bridge',
    bonus: false,
    review: 'The Mudlark is named after the Victorian mudlarks — scavengers who waded into the Thames at low tide to pick through the filth for coins, nails, bones, and anything they could sell. A small, no-fuss pub tucked under the arches near London Bridge with well-kept ales and a useful position between Borough Market and the river.',
    walkToNext: '3 min walk east',
    website: 'https://www.mudlarkpub.co.uk',
  },
  {
    id: 6,
    pubName: 'The Horniman at Hays',
    address: 'Unit 26, Hays Galleria',
    postcode: 'SE1 2HD',
    lat: 51.5057,
    lng: -0.0822,
    landmark: 'Hays Galleria / HMS Belfast',
    bonus: false,
    review: 'The Horniman at Hays occupies a corner of Hays Galleria — the former Hay\'s Wharf, once the largest wharf in the Port of London and known as "the Larder of London." The pub is named after Frederick Horniman, the Victorian tea merchant whose warehouse stood on this site. Recently refurbished with a new mezzanine bar overlooking HMS Belfast. Grand staircase, marble countertops, and a terrace right on the river.',
    walkToNext: '20 min walk east through Bermondsey to bonus pubs',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/thehornimanathayslondonbridge',
  },
  {
    id: 7,
    pubName: 'The Old Justice',
    address: '94 Bermondsey Wall East',
    postcode: 'SE16 4TY',
    lat: 51.5002,
    lng: -0.0642,
    landmark: 'Bermondsey riverside',
    bonus: true,
    review: 'The Old Justice almost didn\'t make it. A developer tried to convert this Grade II listed 1933 pub into flats in 2017, ripping out the Tudor-style panelling without permission. Southwark Council forced a full restoration, and The Old Justice finally reopened in February 2023 under new management. Sir Paul McCartney filmed the "No More Lonely Nights" video here.',
    walkToNext: '5 min walk east',
  },
  {
    id: 8,
    pubName: 'The Angel',
    address: '101 Bermondsey Wall East',
    postcode: 'SE16 4NB',
    lat: 51.5006,
    lng: -0.0590,
    landmark: 'Rotherhithe riverside',
    bonus: true,
    review: 'The Angel is a Grade II listed riverside pub dating to the 1830s, built on the site of a 15th-century monks\' guesthouse. Now a Samuel Smith\'s house — cash only, no music, traditional ales at traditional prices. The upstairs balcony is said to be where Turner painted The Fighting Temeraire. Captain Cook and Samuel Pepys are both associated with the site.',
    walkToNext: '5 min walk south-east',
    website: 'https://www.theangelbermondsey.co.uk',
  },
  {
    id: 9,
    pubName: 'The Mayflower',
    address: '117 Rotherhithe Street',
    postcode: 'SE16 4NF',
    lat: 51.5017,
    lng: -0.0536,
    landmark: 'Rotherhithe / Mayflower mooring',
    bonus: true,
    review: 'The Mayflower sits at the mooring point where the Pilgrim Fathers\' ship departed for America in 1620. The pub opened in 1780 as "The Shippe" and was renamed in 1958. CAMRA\'s Lambeth and Southwark Pub of the Year in 2024 and 2025. The wooden jetty over the Thames, the candlelit dining room, and the real ales make The Mayflower one of the finest riverside pubs in London.',
    walkToNext: null,
    website: 'https://www.themayflowerpub.co.uk',
  },
];

export const southBankStats = {
  totalPubs: southBankPubs.length,
  corePubs: southBankPubs.filter(p => !p.bonus).length,
  bonusPubs: southBankPubs.filter(p => p.bonus).length,
  estimatedTime: '4\u20135 hours (core) + 1 hour (bonus)',
  area: 'South Bank, Bermondsey & Rotherhithe',
};
