import { BasePub } from './types';

export interface SouthBankPub extends BasePub {
  landmark: string;
  walkToNext: string | null;
  bonus: boolean;
}

export const southBankPubs: SouthBankPub[] = [
  {
    id: 1,
    pubName: 'The Black Friar',
    address: '174 Queen Victoria Street',
    postcode: 'EC4V 4EG',
    lat: 51.5121,
    lng: -0.1037,
    landmark: 'Blackfriars Bridge',
    bonus: false,
    review: 'Technically not the South Bank \u2014 the Black Friar sits on the north side of Blackfriars Bridge \u2014 but it\'s two minutes from the river and the best possible way to start a Thames crawl. Built in 1875 on the site of a 13th-century Dominican priory, the interior was overhauled in 1905 by architect Herbert Fuller-Clark into London\'s finest Arts and Crafts pub. Bronze reliefs of jolly monks drinking and singing, marble columns, mother-of-pearl inlays, mosaics with mottos like \u201cContentment surpasses riches.\u201d John Betjeman campaigned to save it from demolition in the 1960s. Spend time looking up \u2014 the detail in here is extraordinary. Then cross the bridge.',
    walkToNext: 'Cross Blackfriars Bridge, 5 min walk',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/theblackfriarblackfriars',
  },
  {
    id: 2,
    pubName: 'Doggett\'s Coat and Badge',
    address: '1 Blackfriars Bridge',
    postcode: 'SE1 9UD',
    lat: 51.5084,
    lng: -0.1048,
    landmark: 'South end of Blackfriars Bridge',
    bonus: false,
    review: 'Named after Thomas Doggett, the 18th-century actor who in 1715 organised a rowing race from London Bridge to Chelsea \u2014 still running, said to be the oldest continuous sporting event in the UK. The winner gets a traditional waterman\'s red coat and silver badge. Doggett\'s Coat and Badge is a 1977 brutalist concrete block at the south end of Blackfriars Bridge, spread over four floors with five bars. It gives almost nothing away from outside. Inside, it was refurbished in early 2024 and the rooftop terrace has panoramic views of St Paul\'s and the City. Ten handpumps on the ground floor. Get up to the top and take the view in before moving on.',
    walkToNext: '8 min walk east along the river',
    website: 'https://www.doggettscoatandbadge.co.uk',
  },
  {
    id: 3,
    pubName: 'Founders Arms',
    address: '52 Hopton Street',
    postcode: 'SE1 9JH',
    lat: 51.5085,
    lng: -0.1019,
    landmark: 'St Paul\'s Cathedral view',
    bonus: false,
    review: 'The Founders Arms was built in 1979 and opened in 1980 by the Dean of St Paul\'s. There is no historical interest here and no pretence otherwise. It\'s a modern glass-fronted Young\'s pub named after the Falcon Iron Foundry that once stood nearby, and you\'re here for one reason: the terrace view of St Paul\'s Cathedral across the river. On a clear afternoon it\'s one of the best pub views in London. Heaters and blankets on the terrace year-round, which tells you everything about the clientele. A good place to settle into the crawl\'s rhythm before the pubs start getting older.',
    walkToNext: '5 min walk east past Tate Modern',
    website: 'https://www.foundersarms.co.uk',
  },
  {
    id: 4,
    pubName: 'The Anchor Bankside',
    address: '34 Park Street',
    postcode: 'SE1 9EF',
    lat: 51.5068,
    lng: -0.0931,
    landmark: 'Shakespeare\'s Globe',
    bonus: false,
    review: 'A pub has stood on this site since the early 1600s, when Bankside was London\'s red-light entertainment district \u2014 theatres, bear pits, and brothels packed in shoulder to shoulder. The Anchor Bankside was the tap room for the Anchor Brewery, established in 1616. Samuel Pepys watched the Great Fire from a tavern here on 2 September 1666. Dr Samuel Johnson was a regular, drinking with Joshua Reynolds and Oliver Goldsmith as guests of the Thrale family who owned the brewery. The current building dates from 1822. Shakespeare\'s Globe is next door. It gets rammed on weekends \u2014 try to time it right.',
    walkToNext: '5 min walk east via Clink Street',
    website: 'https://www.greeneking-pubs.co.uk/pubs/southwark/anchor-bankside',
  },
  {
    id: 5,
    pubName: 'The Mudlark',
    address: '4 Montague Close',
    postcode: 'SE1 9DA',
    lat: 51.5065,
    lng: -0.0890,
    landmark: 'London Bridge',
    bonus: false,
    review: 'The Mudlark is named after the Victorian mudlarks \u2014 destitute children, mostly \u2014 who waded into the Thames at low tide to scavenge coins, nails, bones, anything they could sell. The pub sits under the arches near London Bridge, behind Southwark Cathedral, and has been a favourite of Borough Market traders for years. A small, no-fuss Nicholson\'s pub with well-kept cask ales and a useful position if you want to duck into the market for food. The sign used to show child mudlarks; it now shows a hand holding a coin pulled from the mud.',
    walkToNext: '3 min walk east',
    website: 'https://www.mudlarkpub.co.uk',
  },
  {
    id: 6,
    pubName: 'The Horniman at Hays',
    address: 'Unit 26, Hays Galleria',
    postcode: 'SE1 2HD',
    lat: 51.5057,
    lng: -0.0822,
    landmark: 'Hays Galleria / HMS Belfast',
    bonus: false,
    review: 'The Horniman at Hays occupies a corner of Hays Galleria, formerly Hay\'s Wharf \u2014 once the largest wharf in the Port of London and known as the Larder of London for the volume of tea and provisions that moved through it. The pub is named after Frederick Horniman, the Victorian tea merchant whose warehouse stood on this site. Inside, painted friezes depict Horniman\'s travels to Africa, India, and the Americas. It\'s a big split-level space with a grand staircase, marble countertops, and a terrace directly on the river with HMS Belfast moored across the water. This is the last pub on the core route \u2014 the next three are the bonus stretch into Bermondsey and Rotherhithe.',
    walkToNext: '20 min walk east through Bermondsey to bonus pubs',
    website: 'https://www.nicholsonspubs.co.uk/restaurants/london/thehornimanathayslondonbridge',
  },
  {
    id: 7,
    pubName: 'The Old Justice',
    address: '94 Bermondsey Wall East',
    postcode: 'SE16 4TY',
    lat: 51.5002,
    lng: -0.0642,
    landmark: 'Bermondsey riverside',
    bonus: true,
    review: 'The Old Justice almost didn\'t make it. A developer bought this Grade II listed 1930s pub on Bermondsey Wall East, ripped out the Tudor-style panelling without Listed Building Consent, and tried to convert it into flats. Southwark Council forced a full restoration using salvaged materials, and the pub finally reopened in February 2023 after a six-year closure. The building was designed by architect Sidney C. Clark in 1933 in the brewers\' Tudor style. Paul McCartney filmed the \u201cNo More Lonely Nights\u201d video here. It was also a filming location for The Sweeney. Worth the detour east just for the comeback story.',
    walkToNext: '5 min walk east',
  },
  {
    id: 8,
    pubName: 'The Angel',
    address: '101 Bermondsey Wall East',
    postcode: 'SE16 4NB',
    lat: 51.5006,
    lng: -0.0590,
    landmark: 'Rotherhithe riverside',
    bonus: true,
    review: 'A 15th-century monks\' guesthouse called the Salutation stood on this site before it became The Angel. The current Grade II listed building dates to around 1830 and stands in near-isolation on the Thames Path at the edge of Rotherhithe, with the ruins of Edward III\'s manor house behind it. Now a Samuel Smith\'s pub \u2014 cash only, no music, no TV, traditional ales at prices that feel like a time warp. The upstairs balcony is where Turner supposedly painted The Fighting Temeraire, though Turner scholars will tell you he probably composited the scene from multiple locations. Captain Cook and Samuel Pepys are both claimed as former patrons.',
    walkToNext: '5 min walk south-east',
    website: 'https://www.theangelbermondsey.co.uk',
  },
  {
    id: 9,
    pubName: 'The Mayflower',
    address: '117 Rotherhithe Street',
    postcode: 'SE16 4NF',
    lat: 51.5017,
    lng: -0.0536,
    landmark: 'Rotherhithe / Mayflower mooring',
    bonus: true,
    review: 'The Mayflower sits at the mooring point where the Pilgrim Fathers\' ship departed for America in July 1620 under Captain Christopher Jones, who returned to Rotherhithe and is buried in the churchyard of St Mary\'s nearby. The pub opened in 1780 as The Shippe, was rebuilt in the 19th century, then bombed in the war and refurbished in 1957 with a 16th-century-style interior. It was renamed the Mayflower in 1958. The wooden jetty extends over the Thames \u2014 at high tide the water is directly beneath your feet. CAMRA\'s Lambeth and Southwark Pub of the Year in 2024 and 2025. It\'s also the only pub in England licensed to sell both American and British postage stamps.',
    walkToNext: null,
    website: 'https://www.themayflowerpub.co.uk',
  },
];

export const southBankStats = {
  totalPubs: southBankPubs.length,
  corePubs: southBankPubs.filter(p => !p.bonus).length,
  bonusPubs: southBankPubs.filter(p => p.bonus).length,
  estimatedTime: '4\u20135 hours (core) + 1 hour (bonus)',
  area: 'South Bank, Bermondsey & Rotherhithe',
};
